<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.joda.time.TestAllPackages" time="1.974" tests="433" errors="17" skipped="0" failures="141">
  <properties>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.352-b08"/>
    <property name="java.vm.vendor" value="Private Build"/>
    <property name="maven.multiModuleProjectDirectory" value="/home/sepehr/masters/test_generation/model_generated_coverage/Time1f_automated_2"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/sepehr/masters/test_generation/model_generated_coverage/Time1f_automated_2"/>
    <property name="java.runtime.version" value="1.8.0_352-8u352-ga-1~20.04-b08"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="org.joda.time.DateTimeZone.Provider" value="org.joda.time.tz.UTCProvider"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib"/>
    <property name="maven.conf" value="/usr/share/maven/conf"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="skipTests" value="false"/>
    <property name="os.version" value="5.15.0-58-generic"/>
    <property name="library.jansi.path" value="/usr/share/maven/lib/jansi-native"/>
    <property name="user.home" value="/home/sepehr"/>
    <property name="user.timezone" value="America/Edmonton"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="testFailureIgnore" value="true"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="user.name" value="sepehr"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-openjdk-amd64/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher clean clover:setup test clover:aggregate clover:clover -DskipTests=false -DtestFailureIgnore=true -fail-never"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_352"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes"/>
    <property name="java.vendor" value="Private Build"/>
    <property name="java.specification.maintenance.version" value="4"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.desktop" value="gnome"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="test_setHourOfDay224" classname="org.joda.time.TestChronology" time="0.022"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0.001">
    <failure message="No tests found in org.joda.time.TestDateTimeFieldType" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestDateTimeFieldType
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testIsSupported_DurationFieldType417" classname="org.joda.time.TestDurationFieldType" time="0.001"/>
  <testcase name="testWithFieldAdded_DurationFieldType_int_8418" classname="org.joda.time.TestDurationFieldType" time="0.002"/>
  <testcase name="test_weeks420" classname="org.joda.time.TestDurationFieldType" time="0.065"/>
  <testcase name="test_seconds421" classname="org.joda.time.TestDurationFieldType" time="0.001"/>
  <testcase name="test_centuries419" classname="org.joda.time.TestDurationFieldType" time="0.001"/>
  <testcase name="testConstructor_nullObject293" classname="org.joda.time.TestInstant_Constructors" time="0.011"/>
  <testcase name="testToInstant295" classname="org.joda.time.TestInstant_Basics" time="0.001"/>
  <testcase name="testToDateTime_DateTimeZone292" classname="org.joda.time.TestInstant_Basics" time="0.001"/>
  <testcase name="test_now_nullDateTimeZone249" classname="org.joda.time.TestDateTime_Constructors" time="0.002"/>
  <testcase name="testWithDate_int_int251" classname="org.joda.time.TestDateTime_Basics" time="0.004">
    <error message="Value 24 for monthOfYear must be in the range [1,12]" type="org.joda.time.IllegalFieldValueException">org.joda.time.IllegalFieldValueException: Value 24 for monthOfYear must be in the range [1,12]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:236)
	at org.joda.time.chrono.BasicMonthOfYearDateTimeField.set(BasicMonthOfYearDateTimeField.java:299)
	at org.joda.time.chrono.GJChronology$CutoverField.set(GJChronology.java:752)
	at org.joda.time.chrono.LimitChronology$LimitDateTimeField.set(LimitChronology.java:511)
	at org.joda.time.DateTime.withDate(DateTime.java:712)
	at org.joda.time.TestDateTime_Basics.__CLR4_4_1gxhkxbh99(TestDateTime_Basics.java:132)
	at org.joda.time.TestDateTime_Basics.testWithDate_int_int251(TestDateTime_Basics.java:130)
</error>
  </testcase>
  <testcase name="testWithFields_RPartial252" classname="org.joda.time.TestDateTime_Basics" time="0.003"/>
  <testcase name="testWithField1254" classname="org.joda.time.TestDateTime_Basics" time="0.003"/>
  <testcase name="testPlus_RP257" classname="org.joda.time.TestDateTime_Basics" time="0.004">
    <failure message="expected:&lt;2003-07-28T01:02:03.004-00:01:15&gt; but was:&lt;2003-07-28T06:08:10.012-00:01:15&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<2003-07-28T01:02:03.004-00:01:15> but was:<2003-07-28T06:08:10.012-00:01:15>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestDateTime_Basics.__CLR4_4_1vn8olmhaa(TestDateTime_Basics.java:177)
	at org.joda.time.TestDateTime_Basics.testPlus_RP257(TestDateTime_Basics.java:173)
]]></failure>
  </testcase>
  <testcase name="testWithDurationAdded_RD_int255" classname="org.joda.time.TestDateTime_Basics" time="0.004"/>
  <testcase name="testMinus_long260" classname="org.joda.time.TestDateTime_Basics" time="0"/>
  <testcase name="testPropertyAddLongDayOfWeek263" classname="org.joda.time.TestDateTime_Properties" time="0.006">
    <failure message="expected:&lt;2004-[12-09T00:00:00.000Z]&gt; but was:&lt;2004-[06-18T00:00:00.000+01:00]&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<2004-[12-09T00:00:00.000Z]> but was:<2004-[06-18T00:00:00.000+01:00]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestDateTime_Properties.__CLR4_4_1b009izhd5(TestDateTime_Properties.java:136)
	at org.joda.time.TestDateTime_Properties.testPropertyAddLongDayOfWeek263(TestDateTime_Properties.java:132)
]]></failure>
  </testcase>
  <testcase name="testPropertySetDayOfWeek262" classname="org.joda.time.TestDateTime_Properties" time="0.001">
    <failure message="expected:&lt;2004-0[1-19T00:00:00.000Z]&gt; but was:&lt;2004-0[6-10T00:00:00.000+01:00]&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<2004-0[1-19T00:00:00.000Z]> but was:<2004-0[6-10T00:00:00.000+01:00]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestDateTime_Properties.__CLR4_4_1ffswevhcu(TestDateTime_Properties.java:120)
	at org.joda.time.TestDateTime_Properties.testPropertySetDayOfWeek262(TestDateTime_Properties.java:116)
]]></failure>
  </testcase>
  <testcase name="testPropertyGetCenturyOfEra261" classname="org.joda.time.TestDateTime_Properties" time="0.002"/>
  <testcase name="testPropertyWithMaximumValueDayOfMonth264" classname="org.joda.time.TestDateTime_Properties" time="0.001"/>
  <testcase name="testPropertyWithMaximumValueMillisOfDayDSTGap265" classname="org.joda.time.TestDateTime_Properties" time="0.008">
    <failure message="expected:&lt;2001-04-20T[01:00:00.000]+03:00&gt; but was:&lt;2001-04-20T[23:59:59.999]+03:00&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<2001-04-20T[01:00:00.000]+03:00> but was:<2001-04-20T[23:59:59.999]+03:00>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestDateTime_Properties.__CLR4_4_1w1eweyhdl(TestDateTime_Properties.java:154)
	at org.joda.time.TestDateTime_Properties.testPropertyWithMaximumValueMillisOfDayDSTGap265(TestDateTime_Properties.java:150)
]]></failure>
  </testcase>
  <testcase name="test_now_nullDateTimeZone423" classname="org.joda.time.TestMutableDateTime_Constructors" time="0.002"/>
  <testcase name="testConstructor_badconverterObject_DateTimeZone424" classname="org.joda.time.TestMutableDateTime_Constructors" time="0.002"/>
  <testcase name="test_now422" classname="org.joda.time.TestMutableDateTime_Constructors" time="0"/>
  <testcase name="testCopy444" classname="org.joda.time.TestMutableDateTime_Basics" time="0.001"/>
  <testcase name="testSetMillisOfDay_int1431" classname="org.joda.time.TestMutableDateTime_Sets" time="0.003">
    <failure message="expected:&lt;2002-06-09T00:00:[13.008]+01:00&gt; but was:&lt;2002-06-09T00:00:[00.013]+01:00&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<2002-06-09T00:00:[13.008]+01:00> but was:<2002-06-09T00:00:[00.013]+01:00>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestMutableDateTime_Sets.__CLR4_4_1oekv9jisf(TestMutableDateTime_Sets.java:145)
	at org.joda.time.TestMutableDateTime_Sets.testSetMillisOfDay_int1431(TestMutableDateTime_Sets.java:142)
]]></failure>
  </testcase>
  <testcase name="testSetWeekyear_int2427" classname="org.joda.time.TestMutableDateTime_Sets" time="0.002">
    <failure type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.fail(Assert.java:53)
	at org.joda.time.TestMutableDateTime_Sets.__CLR4_4_16euhflirs(TestMutableDateTime_Sets.java:115)
	at org.joda.time.TestMutableDateTime_Sets.testSetWeekyear_int2427(TestMutableDateTime_Sets.java:111)
</failure>
  </testcase>
  <testcase name="testSetMillisOfSecond_int1432" classname="org.joda.time.TestMutableDateTime_Sets" time="0.002">
    <failure message="expected:&lt;2002-06-09T05:06:[13.008]+01:00&gt; but was:&lt;2002-06-09T05:06:[07.013]+01:00&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<2002-06-09T05:06:[13.008]+01:00> but was:<2002-06-09T05:06:[07.013]+01:00>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestMutableDateTime_Sets.__CLR4_4_1r94flyisj(TestMutableDateTime_Sets.java:150)
	at org.joda.time.TestMutableDateTime_Sets.testSetMillisOfSecond_int1432(TestMutableDateTime_Sets.java:147)
]]></failure>
  </testcase>
  <testcase name="testSetDate_int_int_int_dstOverlapWinter_addZero435" classname="org.joda.time.TestMutableDateTime_Sets" time="0.005">
    <failure message="expected:&lt;...10-30T02:30:00.000+0[1]:00&gt; but was:&lt;...10-30T02:30:00.000+0[2]:00&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<...10-30T02:30:00.000+0[1]:00> but was:<...10-30T02:30:00.000+0[2]:00>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestMutableDateTime_Sets.__CLR4_4_18w7oqtist(TestMutableDateTime_Sets.java:164)
	at org.joda.time.TestMutableDateTime_Sets.testSetDate_int_int_int_dstOverlapWinter_addZero435(TestMutableDateTime_Sets.java:159)
]]></failure>
  </testcase>
  <testcase name="testSetTime_int_int_int_int1436" classname="org.joda.time.TestMutableDateTime_Sets" time="0.001"/>
  <testcase name="testSetDate_int_int_dstOverlapWinter_addZero433" classname="org.joda.time.TestMutableDateTime_Sets" time="0.002">
    <failure message="expected:&lt;...10-30T02:30:00.000+0[1]:00&gt; but was:&lt;...10-30T02:30:00.000+0[2]:00&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<...10-30T02:30:00.000+0[1]:00> but was:<...10-30T02:30:00.000+0[2]:00>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestMutableDateTime_Sets.__CLR4_4_15gnuo9isn(TestMutableDateTime_Sets.java:157)
	at org.joda.time.TestMutableDateTime_Sets.testSetDate_int_int_dstOverlapWinter_addZero433(TestMutableDateTime_Sets.java:152)
]]></failure>
  </testcase>
  <testcase name="testSet_DateTimeFieldType_int2425" classname="org.joda.time.TestMutableDateTime_Sets" time="0.001"/>
  <testcase name="testSetDayOfMonth_int_dstOverlapWinter_addZero429" classname="org.joda.time.TestMutableDateTime_Sets" time="0.002">
    <error message="Value 303 for dayOfMonth must be in the range [1,31]" type="org.joda.time.IllegalFieldValueException">org.joda.time.IllegalFieldValueException: Value 303 for dayOfMonth must be in the range [1,31]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:236)
	at org.joda.time.field.PreciseDurationDateTimeField.set(PreciseDurationDateTimeField.java:79)
	at org.joda.time.chrono.ZonedChronology$ZonedDateTimeField.set(ZonedChronology.java:481)
	at org.joda.time.MutableDateTime.setDayOfMonth(MutableDateTime.java:754)
	at org.joda.time.TestMutableDateTime_Sets.__CLR4_4_1tz3wg1is3(TestMutableDateTime_Sets.java:130)
	at org.joda.time.TestMutableDateTime_Sets.testSetDayOfMonth_int_dstOverlapWinter_addZero429(TestMutableDateTime_Sets.java:126)
</error>
  </testcase>
  <testcase name="testSetMinuteOfDay_int2430" classname="org.joda.time.TestMutableDateTime_Sets" time="0.002">
    <failure type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.fail(Assert.java:53)
	at org.joda.time.TestMutableDateTime_Sets.__CLR4_4_14pzn8pis9(TestMutableDateTime_Sets.java:137)
	at org.joda.time.TestMutableDateTime_Sets.testSetMinuteOfDay_int2430(TestMutableDateTime_Sets.java:133)
</failure>
  </testcase>
  <testcase name="testSetDayOfMonth_int_dstOverlapSummer_addZero428" classname="org.joda.time.TestMutableDateTime_Sets" time="0.003">
    <error message="Value 303 for dayOfMonth must be in the range [1,31]" type="org.joda.time.IllegalFieldValueException">org.joda.time.IllegalFieldValueException: Value 303 for dayOfMonth must be in the range [1,31]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:236)
	at org.joda.time.field.PreciseDurationDateTimeField.set(PreciseDurationDateTimeField.java:79)
	at org.joda.time.chrono.ZonedChronology$ZonedDateTimeField.set(ZonedChronology.java:481)
	at org.joda.time.MutableDateTime.setDayOfMonth(MutableDateTime.java:754)
	at org.joda.time.TestMutableDateTime_Sets.__CLR4_4_1que14kiry(TestMutableDateTime_Sets.java:123)
	at org.joda.time.TestMutableDateTime_Sets.testSetDayOfMonth_int_dstOverlapSummer_addZero428(TestMutableDateTime_Sets.java:120)
</error>
  </testcase>
  <testcase name="testAdd_DurationFieldType_int1426" classname="org.joda.time.TestMutableDateTime_Adds" time="0.001"/>
  <testcase name="testPropertySetWeekOfWeekyear516" classname="org.joda.time.TestMutableDateTime_Properties" time="0.002"/>
  <testcase name="testPropertyGetYearOfCentury437" classname="org.joda.time.TestMutableDateTime_Properties" time="0.005">
    <failure message="expected:&lt;2004&gt; but was:&lt;4&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<2004> but was:<4>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutableDateTime_Properties.__CLR4_4_14xkjseind(TestMutableDateTime_Properties.java:97)
	at org.joda.time.TestMutableDateTime_Properties.testPropertyGetYearOfCentury437(TestMutableDateTime_Properties.java:92)
]]></failure>
  </testcase>
  <testcase name="testPropertyGetMinuteOfDay440" classname="org.joda.time.TestMutableDateTime_Properties" time="0.002">
    <failure message="expected:&lt;53&gt; but was:&lt;803&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<53> but was:<803>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutableDateTime_Properties.__CLR4_4_1q724adio8(TestMutableDateTime_Properties.java:135)
	at org.joda.time.TestMutableDateTime_Properties.testPropertyGetMinuteOfDay440(TestMutableDateTime_Properties.java:129)
]]></failure>
  </testcase>
  <testcase name="testPropertyGetMinuteOfHour441" classname="org.joda.time.TestMutableDateTime_Properties" time="0.002">
    <failure message="expected:&lt;53&gt; but was:&lt;23&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<53> but was:<23>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutableDateTime_Properties.__CLR4_4_1s9j1iioo(TestMutableDateTime_Properties.java:152)
	at org.joda.time.TestMutableDateTime_Properties.testPropertyGetMinuteOfHour441(TestMutableDateTime_Properties.java:146)
]]></failure>
  </testcase>
  <testcase name="testPropertyGetSecondOfDay442" classname="org.joda.time.TestMutableDateTime_Properties" time="0.002">
    <failure message="expected:&lt;53&gt; but was:&lt;48223&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<53> but was:<48223>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutableDateTime_Properties.__CLR4_4_1r3uatzip4(TestMutableDateTime_Properties.java:169)
	at org.joda.time.TestMutableDateTime_Properties.testPropertyGetSecondOfDay442(TestMutableDateTime_Properties.java:163)
]]></failure>
  </testcase>
  <testcase name="testPropertyAddWrapFieldYear447" classname="org.joda.time.TestMutableDateTime_Properties" time="0.002">
    <failure message="expected:&lt;200[4]-06-09T00:00:00.000+...&gt; but was:&lt;200[5]-06-09T00:00:00.000+...&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<200[4]-06-09T00:00:00.000+...> but was:<200[5]-06-09T00:00:00.000+...>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestMutableDateTime_Properties.__CLR4_4_18wba51ipk(TestMutableDateTime_Properties.java:183)
	at org.joda.time.TestMutableDateTime_Properties.testPropertyAddWrapFieldYear447(TestMutableDateTime_Properties.java:180)
]]></failure>
  </testcase>
  <testcase name="testPropertyAddWrapFieldYear448" classname="org.joda.time.TestMutableDateTime_Properties" time="0.002">
    <failure message="expected:&lt;200[4]-06-09T00:00:00.000+...&gt; but was:&lt;200[8]-06-09T00:00:00.000+...&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<200[4]-06-09T00:00:00.000+...> but was:<200[8]-06-09T00:00:00.000+...>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestMutableDateTime_Properties.__CLR4_4_15nbbckipx(TestMutableDateTime_Properties.java:197)
	at org.joda.time.TestMutableDateTime_Properties.testPropertyAddWrapFieldYear448(TestMutableDateTime_Properties.java:194)
]]></failure>
  </testcase>
  <testcase name="testPropertyCompareToDayOfYear439" classname="org.joda.time.TestMutableDateTime_Properties" time="0.001"/>
  <testcase name="testPropertyRoundCeilingHourOfDay449" classname="org.joda.time.TestMutableDateTime_Properties" time="0.002">
    <failure message="expected:&lt;2004-06-09T1[3]:00:00.000+01:00&gt; but was:&lt;2004-06-09T1[4]:00:00.000+01:00&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<2004-06-09T1[3]:00:00.000+01:00> but was:<2004-06-09T1[4]:00:00.000+01:00>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestMutableDateTime_Properties.__CLR4_4_19oc617iq1(TestMutableDateTime_Properties.java:202)
	at org.joda.time.TestMutableDateTime_Properties.testPropertyRoundCeilingHourOfDay449(TestMutableDateTime_Properties.java:199)
]]></failure>
  </testcase>
  <testcase name="testPropertyRoundHalfFloorHourOfDay451" classname="org.joda.time.TestMutableDateTime_Properties" time="0.001"/>
  <testcase name="testPropertyRoundCeilingHourOfDay450" classname="org.joda.time.TestMutableDateTime_Properties" time="0.002">
    <failure message="expected:&lt;2004-06-09T1[3]:00:00.000+01:00&gt; but was:&lt;2004-06-09T1[4]:00:00.000+01:00&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<2004-06-09T1[3]:00:00.000+01:00> but was:<2004-06-09T1[4]:00:00.000+01:00>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestMutableDateTime_Properties.__CLR4_4_197gylxiq5(TestMutableDateTime_Properties.java:207)
	at org.joda.time.TestMutableDateTime_Properties.testPropertyRoundCeilingHourOfDay450(TestMutableDateTime_Properties.java:204)
]]></failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestDateMidnight_Constructors" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestDateMidnight_Constructors
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testMinus_RP621" classname="org.joda.time.TestDateMidnight_Basics" time="0.005">
    <failure message="expected:&lt;2001-03-26T00:00:00.000-00:01:15&gt; but was:&lt;2001-03-25T00:00:00.000-00:01:15&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<2001-03-26T00:00:00.000-00:01:15> but was:<2001-03-25T00:00:00.000-00:01:15>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestDateMidnight_Basics.__CLR4_4_1f7tlvhgxq(TestDateMidnight_Basics.java:195)
	at org.joda.time.TestDateMidnight_Basics.testMinus_RP621(TestDateMidnight_Basics.java:191)
]]></failure>
  </testcase>
  <testcase name="testMinus_RD620" classname="org.joda.time.TestDateMidnight_Basics" time="0.001"/>
  <testcase name="testEqualsHashCode_ISO132" classname="org.joda.time.TestDateMidnight_Basics" time="0.001"/>
  <testcase name="testWithFieldAdded4618" classname="org.joda.time.TestDateMidnight_Basics" time="0"/>
  <testcase name="testPlusWeeks_int619" classname="org.joda.time.TestDateMidnight_Basics" time="0.002">
    <failure message="expected:&lt;2002-05-04T00:00:00.000-00:01:15&gt; but was:&lt;2002-05-10T00:00:00.000-00:01:15&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<2002-05-04T00:00:00.000-00:01:15> but was:<2002-05-10T00:00:00.000-00:01:15>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestDateMidnight_Basics.__CLR4_4_1zb8yqmgxc(TestDateMidnight_Basics.java:179)
	at org.joda.time.TestDateMidnight_Basics.testPlusWeeks_int619(TestDateMidnight_Basics.java:175)
]]></failure>
  </testcase>
  <testcase name="testConstructor616" classname="org.joda.time.TestDateMidnight_Basics" time="0.002"/>
  <testcase name="testWithField1617" classname="org.joda.time.TestDateMidnight_Basics" time="0"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0.002">
    <failure message="No tests found in org.joda.time.TestDateMidnight_Properties" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestDateMidnight_Properties
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testFactory_standardSeconds_long115" classname="org.joda.time.TestDuration_Constructors" time="0.004">
    <failure message="expected:&lt;3600000&gt; but was:&lt;1000&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<3600000> but was:<1000>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:133)
	at junit.framework.Assert.assertEquals(Assert.java:139)
	at org.joda.time.TestDuration_Constructors.__CLR4_4_17bkq78hlh(TestDuration_Constructors.java:103)
	at org.joda.time.TestDuration_Constructors.testFactory_standardSeconds_long115(TestDuration_Constructors.java:101)
]]></failure>
  </testcase>
  <testcase name="testConstructor_RI_RI1276" classname="org.joda.time.TestDuration_Constructors" time="0"/>
  <testcase name="testToString602" classname="org.joda.time.TestDuration_Basics" time="0">
    <failure message="expected:&lt;PT[12.6]S&gt; but was:&lt;PT[0.123]S&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<PT[12.6]S> but was:<PT[0.123]S>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestDuration_Basics.__CLR4_4_1vn9tenhj1(TestDuration_Basics.java:191)
	at org.joda.time.TestDuration_Basics.testToString602(TestDuration_Basics.java:189)
]]></failure>
  </testcase>
  <testcase name="testToString604" classname="org.joda.time.TestDuration_Basics" time="0.002">
    <failure message="expected:&lt;PT[12.6]S&gt; but was:&lt;PT[0.123]S&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<PT[12.6]S> but was:<PT[0.123]S>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestDuration_Basics.__CLR4_4_1p59vtphk3(TestDuration_Basics.java:231)
	at org.joda.time.TestDuration_Basics.testToString604(TestDuration_Basics.java:229)
]]></failure>
  </testcase>
  <testcase name="testToString603" classname="org.joda.time.TestDuration_Basics" time="0.002">
    <failure message="expected:&lt;PT[123L]&gt; but was:&lt;PT[0.123S]&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<PT[123L]> but was:<PT[0.123S]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestDuration_Basics.__CLR4_4_1se9um6hji(TestDuration_Basics.java:209)
	at org.joda.time.TestDuration_Basics.testToString603(TestDuration_Basics.java:207)
]]></failure>
  </testcase>
  <testcase name="testPlus_RD3119" classname="org.joda.time.TestDuration_Basics" time="0"/>
  <testcase name="testMinus_long1118" classname="org.joda.time.TestDuration_Basics" time="0"/>
  <testcase name="testMultipliedBy_long2120" classname="org.joda.time.TestDuration_Basics" time="0.002"/>
  <testcase name="testToPeriod_Chronology277" classname="org.joda.time.TestDuration_Basics" time="0.003"/>
  <testcase name="testToPeriod_PeriodType278" classname="org.joda.time.TestDuration_Basics" time="0.012">
    <failure message="expected:&lt;P64W2DT5H6M7S&gt; but was:&lt;PT10805H6M7S&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<P64W2DT5H6M7S> but was:<PT10805H6M7S>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestDuration_Basics.__CLR4_4_128fjihi1(TestDuration_Basics.java:149)
	at org.joda.time.TestDuration_Basics.testToPeriod_PeriodType278(TestDuration_Basics.java:145)
]]></failure>
  </testcase>
  <testcase name="testToPeriodFrom280" classname="org.joda.time.TestDuration_Basics" time="0.001"/>
  <testcase name="testToDuration600" classname="org.joda.time.TestDuration_Basics" time="0"/>
  <testcase name="testToDuration601" classname="org.joda.time.TestDuration_Basics" time="0.001"/>
  <testcase name="testConstructor_RI_RD245" classname="org.joda.time.TestDuration_Basics" time="0.001"/>
  <testcase name="testToDuration117" classname="org.joda.time.TestDuration_Basics" time="0.001"/>
  <testcase name="testConstructor_Object3146" classname="org.joda.time.TestInterval_Constructors" time="0.009"/>
  <testcase name="testAdd_RInterval1489" classname="org.joda.time.TestInterval_Basics" time="0"/>
  <testcase name="testGap_RInterval_zone147" classname="org.joda.time.TestInterval_Basics" time="0"/>
  <testcase name="testConstructor_long_long_Chronology143" classname="org.joda.time.TestInterval_Basics" time="0"/>
  <testcase name="testConstructor_trickyDifferences_RI_RI_toFeb_exactMonths44" classname="org.joda.time.TestInterval_Basics" time="0.009"/>
  <testcase name="testWithDurationAfterStart4149" classname="org.joda.time.TestInterval_Basics" time="0"/>
  <testcase name="testWithDurationBeforeEnd4150" classname="org.joda.time.TestInterval_Basics" time="0"/>
  <testcase name="testWithPeriodAfterStart1151" classname="org.joda.time.TestInterval_Basics" time="0"/>
  <testcase name="testIsBefore_RInterval_null484" classname="org.joda.time.TestInterval_Basics" time="0"/>
  <testcase name="testAbuts_RInterval_null148" classname="org.joda.time.TestInterval_Basics" time="0"/>
  <testcase name="testFactory_fromDateFields_before1970536" classname="org.joda.time.TestLocalDateTime_Constructors" time="0.014"/>
  <testcase name="testConstructor_Object_nullDateTimeZone537" classname="org.joda.time.TestLocalDateTime_Constructors" time="0.001"/>
  <testcase name="testConstructor_nullObject538" classname="org.joda.time.TestLocalDateTime_Constructors" time="0.001"/>
  <testcase name="testPlus_RP544" classname="org.joda.time.TestLocalDateTime_Basics" time="0.002">
    <failure message="expected:&lt;2003-07-28T10:20:30.040&gt; but was:&lt;2003-07-29T15:26:37.048&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<2003-07-28T10:20:30.040> but was:<2003-07-29T15:26:37.048>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestLocalDateTime_Basics.__CLR4_4_1e866wlhuz(TestLocalDateTime_Basics.java:149)
	at org.joda.time.TestLocalDateTime_Basics.testPlus_RP544(TestLocalDateTime_Basics.java:145)
]]></failure>
  </testcase>
  <testcase name="testToString_String_Locale553" classname="org.joda.time.TestLocalDateTime_Basics" time="0.006">
    <failure message="expected:&lt;[]10:20:30.040&gt; but was:&lt;[2002-06-09T]10:20:30.040&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<[]10:20:30.040> but was:<[2002-06-09T]10:20:30.040>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestLocalDateTime_Basics.__CLR4_4_1y9bap9hwc(TestLocalDateTime_Basics.java:203)
	at org.joda.time.TestLocalDateTime_Basics.testToString_String_Locale553(TestLocalDateTime_Basics.java:200)
]]></failure>
  </testcase>
  <testcase name="testIsSupported_DateTimeFieldType595" classname="org.joda.time.TestLocalDateTime_Basics" time="0.003"/>
  <testcase name="testGetters549" classname="org.joda.time.TestLocalDateTime_Basics" time="0.003">
    <failure message="expected:&lt;1970&gt; but was:&lt;70&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<1970> but was:<70>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestLocalDateTime_Basics.__CLR4_4_18hhpd7hvy(TestLocalDateTime_Basics.java:195)
	at org.joda.time.TestLocalDateTime_Basics.testGetters549(TestLocalDateTime_Basics.java:185)
]]></failure>
  </testcase>
  <testcase name="testGetValue_int539" classname="org.joda.time.TestLocalDateTime_Basics" time="0.001"/>
  <testcase name="testToString_DTFormatter541" classname="org.joda.time.TestLocalDateTime_Basics" time="0.002"/>
  <testcase name="testIsSupported_DurationFieldType542" classname="org.joda.time.TestLocalDateTime_Basics" time="0.002">
    <failure message="expected:&lt;false&gt; but was:&lt;true&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<false> but was:<true>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:146)
	at junit.framework.Assert.assertEquals(Assert.java:152)
	at org.joda.time.TestLocalDateTime_Basics.__CLR4_4_164boyvhuo(TestLocalDateTime_Basics.java:142)
	at org.joda.time.TestLocalDateTime_Basics.testIsSupported_DurationFieldType542(TestLocalDateTime_Basics.java:133)
]]></failure>
  </testcase>
  <testcase name="testPlusDays_int545" classname="org.joda.time.TestLocalDateTime_Basics" time="0.005">
    <failure message="expected:&lt;2002-05-03T10:20:30.040&gt; but was:&lt;2002-05-04T10:20:30.040&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<2002-05-03T10:20:30.040> but was:<2002-05-04T10:20:30.040>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestLocalDateTime_Basics.__CLR4_4_1bxaneehv6(TestLocalDateTime_Basics.java:157)
	at org.joda.time.TestLocalDateTime_Basics.testPlusDays_int545(TestLocalDateTime_Basics.java:153)
]]></failure>
  </testcase>
  <testcase name="testPlusDays_int546" classname="org.joda.time.TestLocalDateTime_Basics" time="0.002"/>
  <testcase name="testMinusYears_int547" classname="org.joda.time.TestLocalDateTime_Basics" time="0.004"/>
  <testcase name="testMinusMinutes_int548" classname="org.joda.time.TestLocalDateTime_Basics" time="0.009">
    <failure message="expected:&lt;2002-05-03T10:20:30.040&gt; but was:&lt;2002-05-03T10:19:30.040&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<2002-05-03T10:20:30.040> but was:<2002-05-03T10:19:30.040>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestLocalDateTime_Basics.__CLR4_4_19r2xrjhvr(TestLocalDateTime_Basics.java:181)
	at org.joda.time.TestLocalDateTime_Basics.testMinusMinutes_int548(TestLocalDateTime_Basics.java:177)
]]></failure>
  </testcase>
  <testcase name="testIsSupported_DateTimeFieldType596" classname="org.joda.time.TestLocalDateTime_Basics" time="0.002"/>
  <testcase name="testPropertyAddToCopyMonth552" classname="org.joda.time.TestLocalDateTime_Properties" time="0.008"/>
  <testcase name="testPropertyWithMinimumValueDayOfMonth556" classname="org.joda.time.TestLocalDateTime_Properties" time="0.002"/>
  <testcase name="testPropertyWithMaximumValueDayOfMonth555" classname="org.joda.time.TestLocalDateTime_Properties" time="0.001"/>
  <testcase name="testConstructor296" classname="org.joda.time.TestLocalDate_Constructors" time="0.001"/>
  <testcase name="testParse_noFormatter297" classname="org.joda.time.TestLocalDate_Constructors" time="0.002"/>
  <testcase name="testParse_noFormatter298" classname="org.joda.time.TestLocalDate_Constructors" time="0.001"/>
  <testcase name="testWithField_DateTimeFieldType_int_1309" classname="org.joda.time.TestLocalDate_Basics" time="0.001"/>
  <testcase name="testWithField_DateTimeFieldType_int_2310" classname="org.joda.time.TestLocalDate_Basics" time="0.001"/>
  <testcase name="testWithFieldAdded_DurationFieldType_int_2311" classname="org.joda.time.TestLocalDate_Basics" time="0.002"/>
  <testcase name="testToDateTime_LocalTime_nullZone306" classname="org.joda.time.TestLocalDate_Basics" time="0.004"/>
  <testcase name="testToInterval_DateTimeZone307" classname="org.joda.time.TestLocalDate_Basics" time="0.002"/>
  <testcase name="testPlusWeeks_int312" classname="org.joda.time.TestLocalDate_Basics" time="0.002"/>
  <testcase name="testPlusDays_int313" classname="org.joda.time.TestLocalDate_Basics" time="0.001"/>
  <testcase name="testMinusMonths_int314" classname="org.joda.time.TestLocalDate_Basics" time="0.023"/>
  <testcase name="testPropertyGetWeekyear100" classname="org.joda.time.TestLocalDate_Basics" time="0.002">
    <failure message="expected:&lt;4&gt; but was:&lt;2004&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<4> but was:<2004>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestLocalDate_Basics.__CLR4_4_19mxi7si1e(TestLocalDate_Basics.java:125)
	at org.joda.time.TestLocalDate_Basics.testPropertyGetWeekyear100(TestLocalDate_Basics.java:119)
]]></failure>
  </testcase>
  <testcase name="testGet_DateTimeFieldType301" classname="org.joda.time.TestLocalDate_Basics" time="0.002">
    <failure message="expected:&lt;1970&gt; but was:&lt;2002&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<1970> but was:<2002>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestLocalDate_Basics.__CLR4_4_1egool9i2l(TestLocalDate_Basics.java:167)
	at org.joda.time.TestLocalDate_Basics.testGet_DateTimeFieldType301(TestLocalDate_Basics.java:165)
]]></failure>
  </testcase>
  <testcase name="testFactory_fromDateFields_before1970299" classname="org.joda.time.TestLocalDate_Basics" time="0.002"/>
  <testcase name="testToLocalDateTime_LocalTime305" classname="org.joda.time.TestLocalDate_Basics" time="0.001"/>
  <testcase name="testToDate_autumnDST302" classname="org.joda.time.TestLocalDate_Basics" time="0.009"/>
  <testcase name="testToDateTimeAtMidnight303" classname="org.joda.time.TestLocalDate_Basics" time="0.001"/>
  <testcase name="testToInterval_DateTimeAtStartOfDay308" classname="org.joda.time.TestLocalDate_Basics" time="0.001"/>
  <testcase name="testPropertyGetEra206" classname="org.joda.time.TestLocalDate_Basics" time="0.009"/>
  <testcase name="testToDateTimeAtMidnight_nullZone304" classname="org.joda.time.TestLocalDate_Basics" time="0.002"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestLocalDate_Properties" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestLocalDate_Properties
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testConstructor_Object_nullChronology402" classname="org.joda.time.TestLocalTime_Constructors" time="0.001"/>
  <testcase name="testFactory_FromDateFields_after1970401" classname="org.joda.time.TestLocalTime_Constructors" time="0.001"/>
  <testcase name="testConstructor_Object_nullChronology406" classname="org.joda.time.TestLocalTime_Constructors" time="0.002"/>
  <testcase name="testConstructor_Object_nullChronology403" classname="org.joda.time.TestLocalTime_Constructors" time="0.001"/>
  <testcase name="testProperty408" classname="org.joda.time.TestLocalTime_Basics" time="0.002"/>
  <testcase name="testPlusSeconds_int414" classname="org.joda.time.TestLocalTime_Basics" time="0.002">
    <failure message="expected:&lt;02:02:04.004&gt; but was:&lt;01:02:04.004&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<02:02:04.004> but was:<01:02:04.004>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestLocalTime_Basics.__CLR4_4_1idzmd7i8w(TestLocalTime_Basics.java:160)
	at org.joda.time.TestLocalTime_Basics.testPlusSeconds_int414(TestLocalTime_Basics.java:156)
]]></failure>
  </testcase>
  <testcase name="testMinusMinutes_int415" classname="org.joda.time.TestLocalTime_Basics" time="0.002"/>
  <testcase name="testMinusSeconds_int416" classname="org.joda.time.TestLocalTime_Basics" time="0.001"/>
  <testcase name="testPlusSeconds_int413" classname="org.joda.time.TestLocalTime_Basics" time="0.005">
    <failure message="expected:&lt;02:02:04.004&gt; but was:&lt;01:02:04.004&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<02:02:04.004> but was:<01:02:04.004>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestLocalTime_Basics.__CLR4_4_1f4znkqi8p(TestLocalTime_Basics.java:152)
	at org.joda.time.TestLocalTime_Basics.testPlusSeconds_int413(TestLocalTime_Basics.java:149)
]]></failure>
  </testcase>
  <testcase name="testWithFieldAdded_DurationFieldType_int_1409" classname="org.joda.time.TestLocalTime_Basics" time="0.003">
    <failure message="expected:&lt;12:20:30.040&gt; but was:&lt;16:20:30.040&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<12:20:30.040> but was:<16:20:30.040>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestLocalTime_Basics.__CLR4_4_11vkut9i83(TestLocalTime_Basics.java:125)
	at org.joda.time.TestLocalTime_Basics.testWithFieldAdded_DurationFieldType_int_1409(TestLocalTime_Basics.java:121)
]]></failure>
  </testcase>
  <testcase name="testPlusMinutes_int412" classname="org.joda.time.TestLocalTime_Basics" time="0.002">
    <failure message="expected:&lt;01:02:03.004&gt; but was:&lt;01:03:03.004&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<01:02:03.004> but was:<01:03:03.004>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestLocalTime_Basics.__CLR4_4_1hh7ftli8i(TestLocalTime_Basics.java:145)
	at org.joda.time.TestLocalTime_Basics.testPlusMinutes_int412(TestLocalTime_Basics.java:141)
]]></failure>
  </testcase>
  <testcase name="testWithFieldAdded_DurationFieldType_int_2411" classname="org.joda.time.TestLocalTime_Basics" time="0.001"/>
  <testcase name="testWithFieldAdded_DurationFieldType_int_1410" classname="org.joda.time.TestLocalTime_Basics" time="0.002">
    <failure message="expected:&lt;15:20:30.040&gt; but was:&lt;16:20:30.040&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<15:20:30.040> but was:<16:20:30.040>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestLocalTime_Basics.__CLR4_4_11epndzi88(TestLocalTime_Basics.java:131)
	at org.joda.time.TestLocalTime_Basics.testWithFieldAdded_DurationFieldType_int_1410(TestLocalTime_Basics.java:127)
]]></failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0.001">
    <failure message="No tests found in org.joda.time.TestLocalTime_Properties" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestLocalTime_Properties
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testConstructor_Object6483" classname="org.joda.time.TestMutableInterval_Constructors" time="0.003"/>
  <testcase name="testPropertyToIntervalYearOfCentury357" classname="org.joda.time.TestMutableInterval_Constructors" time="0.002"/>
  <testcase name="testConstructor_RP_RI8356" classname="org.joda.time.TestMutableInterval_Constructors" time="0.001"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestMutableInterval_Basics" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestMutableInterval_Basics
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testSetDurationBeforeEnd_RI3613" classname="org.joda.time.TestMutableInterval_Updates" time="0.001"/>
  <testcase name="testSetDurationAfterStart_RI3615" classname="org.joda.time.TestMutableInterval_Updates" time="0.001"/>
  <testcase name="testSetInterval_RInterval1610" classname="org.joda.time.TestMutableInterval_Updates" time="0.002">
    <failure message="expected:&lt;1018009440001&gt; but was:&lt;1052231280000&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<1018009440001> but was:<1052231280000>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:133)
	at junit.framework.Assert.assertEquals(Assert.java:139)
	at org.joda.time.TestMutableInterval_Updates.__CLR4_4_1jvut88ix7(TestMutableInterval_Updates.java:105)
	at org.joda.time.TestMutableInterval_Updates.testSetInterval_RInterval1610(TestMutableInterval_Updates.java:101)
]]></failure>
  </testcase>
  <testcase name="testSetInterval_RInterval3611" classname="org.joda.time.TestMutableInterval_Updates" time="0.001">
    <error message="Interval must not be null" type="java.lang.IllegalArgumentException">java.lang.IllegalArgumentException: Interval must not be null
	at org.joda.time.MutableInterval.setInterval(MutableInterval.java:228)
	at org.joda.time.TestMutableInterval_Updates.__CLR4_4_1wu82frixc(TestMutableInterval_Updates.java:109)
	at org.joda.time.TestMutableInterval_Updates.testSetInterval_RInterval3611(TestMutableInterval_Updates.java:107)
</error>
  </testcase>
  <testcase name="testSetInterval_RInterval3612" classname="org.joda.time.TestMutableInterval_Updates" time="0.002">
    <error message="Interval must not be null" type="java.lang.IllegalArgumentException">java.lang.IllegalArgumentException: Interval must not be null
	at org.joda.time.MutableInterval.setInterval(MutableInterval.java:228)
	at org.joda.time.TestMutableInterval_Updates.__CLR4_4_1yxw0qwixh(TestMutableInterval_Updates.java:115)
	at org.joda.time.TestMutableInterval_Updates.testSetInterval_RInterval3612(TestMutableInterval_Updates.java:113)
</error>
  </testcase>
  <testcase name="testFactoryFieldDifference540" classname="org.joda.time.TestPeriod_Constructors" time="0.004">
    <error message="Values array must be the same length as the types array" type="java.lang.IllegalArgumentException"><![CDATA[java.lang.IllegalArgumentException: Values array must be the same length as the types array
	at org.joda.time.Partial.<init>(Partial.java:200)
	at org.joda.time.Partial.<init>(Partial.java:175)
	at org.joda.time.TestPeriod_Constructors.__CLR4_4_1jyh5kpjl3(TestPeriod_Constructors.java:152)
	at org.joda.time.TestPeriod_Constructors.testFactoryFieldDifference540(TestPeriod_Constructors.java:150)
]]></error>
  </testcase>
  <testcase name="testConstructor_RD_RI246" classname="org.joda.time.TestPeriod_Constructors" time="0.001"/>
  <testcase name="testNormalizedStandard_yearMonth147" classname="org.joda.time.TestPeriod_Constructors" time="0.001"/>
  <testcase name="testFactoryFieldDifference136" classname="org.joda.time.TestPeriod_Constructors" time="0.001"/>
  <testcase name="testFactoryFieldDifference537" classname="org.joda.time.TestPeriod_Constructors" time="0.001">
    <error message="Values array must be the same length as the types array" type="java.lang.IllegalArgumentException"><![CDATA[java.lang.IllegalArgumentException: Values array must be the same length as the types array
	at org.joda.time.Partial.<init>(Partial.java:200)
	at org.joda.time.Partial.<init>(Partial.java:175)
	at org.joda.time.TestPeriod_Constructors.__CLR4_4_1czm0khjk5(TestPeriod_Constructors.java:106)
	at org.joda.time.TestPeriod_Constructors.testFactoryFieldDifference537(TestPeriod_Constructors.java:104)
]]></error>
  </testcase>
  <testcase name="testFactoryFieldDifference139" classname="org.joda.time.TestPeriod_Constructors" time="0.001"/>
  <testcase name="testConstructor_Object_PeriodType1322" classname="org.joda.time.TestPeriod_Constructors" time="0.003"/>
  <testcase name="testConstructor_RP_RP_PeriodType8362" classname="org.joda.time.TestPeriod_Constructors" time="0.001"/>
  <testcase name="testToStandardMinutes_months52" classname="org.joda.time.TestPeriod_Basics" time="0.006"/>
  <testcase name="testToStandardSeconds_months53" classname="org.joda.time.TestPeriod_Basics" time="0.002"/>
  <testcase name="testToStandardSeconds321" classname="org.joda.time.TestPeriod_Basics" time="0.001"/>
  <testcase name="testToPeriod323" classname="org.joda.time.TestPeriod_Basics" time="0.001"/>
  <testcase name="testWithFields249" classname="org.joda.time.TestPeriod_Basics" time="0"/>
  <testcase name="testWithFieldAdded350" classname="org.joda.time.TestPeriod_Basics" time="0.003">
    <error message="Period does not support field &apos;years&apos;" type="java.lang.IllegalArgumentException"><![CDATA[java.lang.IllegalArgumentException: Period does not support field 'years'
	at org.joda.time.base.BasePeriod.checkAndUpdate(BasePeriod.java:394)
	at org.joda.time.base.BasePeriod.setPeriodInternal(BasePeriod.java:454)
	at org.joda.time.base.BasePeriod.<init>(BasePeriod.java:93)
	at org.joda.time.Period.<init>(Period.java:352)
	at org.joda.time.TestPeriod_Basics.__CLR4_4_1gj0b13jg3(TestPeriod_Basics.java:141)
	at org.joda.time.TestPeriod_Basics.testWithFieldAdded350(TestPeriod_Basics.java:140)
]]></error>
  </testcase>
  <testcase name="testToStandardWeeks_months51" classname="org.joda.time.TestPeriod_Basics" time="0.002"/>
  <testcase name="testToStandardHours330" classname="org.joda.time.TestPeriod_Basics" time="0.002"/>
  <testcase name="testConstructor_Object3498" classname="org.joda.time.TestPeriod_Basics" time="0.003">
    <failure message="expected:&lt;64&gt; but was:&lt;0&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<64> but was:<0>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestPeriod_Basics.__CLR4_4_1y7ts8tjir(TestPeriod_Basics.java:265)
	at org.joda.time.TestPeriod_Basics.testConstructor_Object3498(TestPeriod_Basics.java:259)
]]></failure>
  </testcase>
  <testcase name="testPlusFields42" classname="org.joda.time.TestPeriod_Basics" time="0"/>
  <testcase name="testConstructor_long_long_Chronology1495" classname="org.joda.time.TestMutablePeriod_Constructors" time="0.003">
    <failure message="expected:&lt;1&gt; but was:&lt;0&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<1> but was:<0>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutablePeriod_Constructors.__CLR4_4_161il2tj0v(TestMutablePeriod_Constructors.java:173)
	at org.joda.time.TestMutablePeriod_Constructors.testConstructor_long_long_Chronology1495(TestMutablePeriod_Constructors.java:161)
]]></failure>
  </testcase>
  <testcase name="testConstructor_RI_RI2496" classname="org.joda.time.TestMutablePeriod_Constructors" time="0.002">
    <failure message="expected:&lt;0&gt; but was:&lt;1&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutablePeriod_Constructors.__CLR4_4_1j7czn6j18(TestMutablePeriod_Constructors.java:181)
	at org.joda.time.TestMutablePeriod_Constructors.testConstructor_RI_RI2496(TestMutablePeriod_Constructors.java:175)
]]></failure>
  </testcase>
  <testcase name="testConstructor_RI_RD2497" classname="org.joda.time.TestMutablePeriod_Constructors" time="0.002"/>
  <testcase name="testConstructor_RI_RD2363" classname="org.joda.time.TestMutablePeriod_Constructors" time="0"/>
  <testcase name="testPropertyToIntervalMillisOfSecond397" classname="org.joda.time.TestMutablePeriod_Constructors" time="0.001"/>
  <testcase name="testSetDays503" classname="org.joda.time.TestMutablePeriod_Constructors" time="0"/>
  <testcase name="testSetYears502" classname="org.joda.time.TestMutablePeriod_Constructors" time="0.002"/>
  <testcase name="testConstructor_long_Chronology2494" classname="org.joda.time.TestMutablePeriod_Constructors" time="0.001">
    <failure message="expected:&lt;64&gt; but was:&lt;0&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<64> but was:<0>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutablePeriod_Constructors.__CLR4_4_12lo9zsj0j(TestMutablePeriod_Constructors.java:154)
	at org.joda.time.TestMutablePeriod_Constructors.testConstructor_long_Chronology2494(TestMutablePeriod_Constructors.java:148)
]]></failure>
  </testcase>
  <testcase name="testConstructor_long_PeriodType_Chronology1493" classname="org.joda.time.TestMutablePeriod_Constructors" time="0.004">
    <failure message="expected:&lt;64&gt; but was:&lt;0&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<64> but was:<0>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutablePeriod_Constructors.__CLR4_4_13z7avgj07(TestMutablePeriod_Constructors.java:141)
	at org.joda.time.TestMutablePeriod_Constructors.testConstructor_long_PeriodType_Chronology1493(TestMutablePeriod_Constructors.java:135)
]]></failure>
  </testcase>
  <testcase name="testConstructor_RI_RD4364" classname="org.joda.time.TestMutablePeriod_Constructors" time="0"/>
  <testcase name="testConstructor_long_long1514" classname="org.joda.time.TestMutablePeriod_Constructors" time="0.003"/>
  <testcase name="testConstructor_RI_RP3570" classname="org.joda.time.TestMutablePeriod_Constructors" time="0.001"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestMutablePeriod_Basics" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestMutablePeriod_Basics
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testAddMinutes506" classname="org.joda.time.TestMutablePeriod_Updates" time="0.003">
    <failure message="expected:&lt;15&gt; but was:&lt;16&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<15> but was:<16>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutablePeriod_Updates.__CLR4_4_1uqlv0uj5o(TestMutablePeriod_Updates.java:167)
	at org.joda.time.TestMutablePeriod_Updates.testAddMinutes506(TestMutablePeriod_Updates.java:164)
]]></failure>
  </testcase>
  <testcase name="testSetWeeks365" classname="org.joda.time.TestMutablePeriod_Updates" time="0.001"/>
  <testcase name="testConstructor_long_PeriodType2492" classname="org.joda.time.TestMutablePeriod_Updates" time="0.002">
    <failure message="expected:&lt;64&gt; but was:&lt;0&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<64> but was:<0>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutablePeriod_Updates.__CLR4_4_1p5yevj4e(TestMutablePeriod_Updates.java:120)
	at org.joda.time.TestMutablePeriod_Updates.testConstructor_long_PeriodType2492(TestMutablePeriod_Updates.java:114)
]]></failure>
  </testcase>
  <testcase name="testAddDays504" classname="org.joda.time.TestMutablePeriod_Updates" time="0.003">
    <failure message="expected:&lt;15&gt; but was:&lt;14&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<15> but was:<14>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutablePeriod_Updates.__CLR4_4_1q7sbjuj5e(TestMutablePeriod_Updates.java:156)
	at org.joda.time.TestMutablePeriod_Updates.testAddDays504(TestMutablePeriod_Updates.java:153)
]]></failure>
  </testcase>
  <testcase name="testSetPeriod_RI_RI2501" classname="org.joda.time.TestMutablePeriod_Updates" time="0.002"/>
  <testcase name="testSetPeriod_8ints1500" classname="org.joda.time.TestMutablePeriod_Updates" time="0.002">
    <failure message="expected:&lt;15&gt; but was:&lt;17&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<15> but was:<17>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMutablePeriod_Updates.__CLR4_4_1m2vty1j4q(TestMutablePeriod_Updates.java:136)
	at org.joda.time.TestMutablePeriod_Updates.testSetPeriod_8ints1500(TestMutablePeriod_Updates.java:127)
]]></failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestBaseSingleFieldPeriod" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestBaseSingleFieldPeriod
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testFactory_parseYears_String281" classname="org.joda.time.TestYears" time="0.004"/>
  <testcase name="testMinus_int282" classname="org.joda.time.TestYears" time="0"/>
  <testcase name="testIsGreaterThan289" classname="org.joda.time.TestYears" time="0.001"/>
  <testcase name="testIsLessThan290" classname="org.joda.time.TestYears" time="0"/>
  <testcase name="testGetPeriodType283" classname="org.joda.time.TestYears" time="0.001"/>
  <testcase name="testNegated288" classname="org.joda.time.TestYears" time="0"/>
  <testcase name="testFactory_yearsBetween_RInstant284" classname="org.joda.time.TestYears" time="0.001"/>
  <testcase name="testToString291" classname="org.joda.time.TestYears" time="0"/>
  <testcase name="testIsLessThan145" classname="org.joda.time.TestMonths" time="0.002"/>
  <testcase name="testSerialization143" classname="org.joda.time.TestMonths" time="0.003"/>
  <testcase name="testDividedBy_int144" classname="org.joda.time.TestMonths" time="0.001"/>
  <testcase name="testFactory_weeksBetween_RPartial247" classname="org.joda.time.TestWeeks" time="0"/>
  <testcase name="testFactory_weeks_int240" classname="org.joda.time.TestWeeks" time="0"/>
  <testcase name="testFactory_parseWeeks_String244" classname="org.joda.time.TestWeeks" time="0.002">
    <error message="Invalid format: &quot;P2W0M&quot; is malformed at &quot;0M&quot;" type="java.lang.IllegalArgumentException">java.lang.IllegalArgumentException: Invalid format: "P2W0M" is malformed at "0M"
	at org.joda.time.format.PeriodFormatter.parseMutablePeriod(PeriodFormatter.java:326)
	at org.joda.time.format.PeriodFormatter.parsePeriod(PeriodFormatter.java:304)
	at org.joda.time.Weeks.parseWeeks(Weeks.java:185)
	at org.joda.time.TestWeeks.__CLR4_4_132yijgjwk(TestWeeks.java:93)
	at org.joda.time.TestWeeks.testFactory_parseWeeks_String244(TestWeeks.java:87)
</error>
  </testcase>
  <testcase name="testGetPeriodType455" classname="org.joda.time.TestWeeks" time="0"/>
  <testcase name="testFactory_weeksBetween_RInstant242" classname="org.joda.time.TestWeeks" time="0.001"/>
  <testcase name="testSerialization246" classname="org.joda.time.TestWeeks" time="0.001"/>
  <testcase name="testToStandardHours248" classname="org.joda.time.TestWeeks" time="0.002">
    <failure message="expected:&lt;PT1209600H&gt; but was:&lt;PT336H&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<PT1209600H> but was:<PT336H>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestWeeks.__CLR4_4_1nd7skojxj(TestWeeks.java:132)
	at org.joda.time.TestWeeks.testToStandardHours248(TestWeeks.java:129)
]]></failure>
  </testcase>
  <testcase name="testFactory_hours_int452" classname="org.joda.time.TestWeeks" time="0"/>
  <testcase name="testGetMethods453" classname="org.joda.time.TestWeeks" time="0.001"/>
  <testcase name="testMinus_int241" classname="org.joda.time.TestWeeks" time="0.001"/>
  <testcase name="testPlus_Days519" classname="org.joda.time.TestDays" time="0.001"/>
  <testcase name="testToStandardHours517" classname="org.joda.time.TestDays" time="0.001">
    <failure message="expected:&lt;PT172800H&gt; but was:&lt;PT48H&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<PT172800H> but was:<PT48H>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestDays.__CLR4_4_1jvvkd9hdy(TestDays.java:58)
	at org.joda.time.TestDays.testToStandardHours517(TestDays.java:55)
]]></failure>
  </testcase>
  <testcase name="testIsGreaterThan458" classname="org.joda.time.TestHours" time="0.002"/>
  <testcase name="testToStandardDays456" classname="org.joda.time.TestHours" time="0">
    <failure message="expected:&lt;P2D&gt; but was:&lt;P3600000D&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<P2D> but was:<P3600000D>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestHours.__CLR4_4_1utpr0lhma(TestHours.java:69)
	at org.joda.time.TestHours.testToStandardDays456(TestHours.java:66)
]]></failure>
  </testcase>
  <testcase name="testFactory_hoursBetween_RPartial454" classname="org.joda.time.TestHours" time="0.003">
    <failure message="expected:&lt;3&gt; but was:&lt;0&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<3> but was:<0>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestHours.__CLR4_4_1853ux8hm1(TestHours.java:60)
	at org.joda.time.TestHours.testFactory_hoursBetween_RPartial454(TestHours.java:55)
]]></failure>
  </testcase>
  <testcase name="testToStandardDuration457" classname="org.joda.time.TestHours" time="0"/>
  <testcase name="testToStandardWeeks389" classname="org.joda.time.TestMinutes" time="0.001">
    <failure message="expected:&lt;P2W&gt; but was:&lt;P0W&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<P2W> but was:<P0W>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestMinutes.__CLR4_4_1gutzxiidq(TestMinutes.java:148)
	at org.joda.time.TestMinutes.testToStandardWeeks389(TestMinutes.java:145)
]]></failure>
  </testcase>
  <testcase name="testMinus_Minutes390" classname="org.joda.time.TestMinutes" time="0.001"/>
  <testcase name="testFactory_minutesBetween_RPartial384" classname="org.joda.time.TestMinutes" time="0.003">
    <failure message="expected:&lt;3&gt; but was:&lt;0&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<3> but was:<0>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMinutes.__CLR4_4_1grf8woicf(TestMinutes.java:89)
	at org.joda.time.TestMinutes.testFactory_minutesBetween_RPartial384(TestMinutes.java:84)
]]></failure>
  </testcase>
  <testcase name="testIsLessThan381" classname="org.joda.time.TestMinutes" time="0"/>
  <testcase name="testMinus_int382" classname="org.joda.time.TestMinutes" time="0"/>
  <testcase name="testFactory_parseMinutes_String386" classname="org.joda.time.TestMinutes" time="0.001">
    <error message="Period does not support field &apos;months&apos;" type="java.lang.IllegalArgumentException">java.lang.IllegalArgumentException: Period does not support field 'months'
	at org.joda.time.base.BasePeriod.setFieldInto(BasePeriod.java:489)
	at org.joda.time.base.BasePeriod.setField(BasePeriod.java:474)
	at org.joda.time.MutablePeriod.setMonths(MutablePeriod.java:843)
	at org.joda.time.format.PeriodFormatterBuilder$FieldFormatter.setFieldValue(PeriodFormatterBuilder.java:1511)
	at org.joda.time.format.PeriodFormatterBuilder$FieldFormatter.parseInto(PeriodFormatterBuilder.java:1308)
	at org.joda.time.format.PeriodFormatterBuilder$Composite.parseInto(PeriodFormatterBuilder.java:1837)
	at org.joda.time.format.PeriodFormatterBuilder$Separator.parseInto(PeriodFormatterBuilder.java:1709)
	at org.joda.time.format.PeriodFormatter.parseMutablePeriod(PeriodFormatter.java:318)
	at org.joda.time.format.PeriodFormatter.parsePeriod(PeriodFormatter.java:304)
	at org.joda.time.Minutes.parseMinutes(Minutes.java:185)
	at org.joda.time.TestMinutes.__CLR4_4_1l2pobpid1(TestMinutes.java:118)
	at org.joda.time.TestMinutes.testFactory_parseMinutes_String386(TestMinutes.java:113)
</error>
  </testcase>
  <testcase name="testFactory_minutes_int383" classname="org.joda.time.TestMinutes" time="0"/>
  <testcase name="testFactory_minutesBetween_RPartial387" classname="org.joda.time.TestMinutes" time="0.002">
    <failure message="expected:&lt;3&gt; but was:&lt;4320&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<3> but was:<4320>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMinutes.__CLR4_4_1qif5a3ide(TestMinutes.java:135)
	at org.joda.time.TestMinutes.testFactory_minutesBetween_RPartial387(TestMinutes.java:131)
]]></failure>
  </testcase>
  <testcase name="testGetFieldType388" classname="org.joda.time.TestMinutes" time="0"/>
  <testcase name="testFactory_parseMinutes_String385" classname="org.joda.time.TestMinutes" time="0.002">
    <error message="Period does not support field &apos;seconds&apos;" type="java.lang.IllegalArgumentException">java.lang.IllegalArgumentException: Period does not support field 'seconds'
	at org.joda.time.base.BasePeriod.setFieldInto(BasePeriod.java:489)
	at org.joda.time.base.BasePeriod.setField(BasePeriod.java:474)
	at org.joda.time.MutablePeriod.setSeconds(MutablePeriod.java:953)
	at org.joda.time.format.PeriodFormatterBuilder$FieldFormatter.setFieldValue(PeriodFormatterBuilder.java:1526)
	at org.joda.time.format.PeriodFormatterBuilder$FieldFormatter.parseInto(PeriodFormatterBuilder.java:1310)
	at org.joda.time.format.PeriodFormatterBuilder$Composite.parseInto(PeriodFormatterBuilder.java:1837)
	at org.joda.time.format.PeriodFormatterBuilder$Separator.parseInto(PeriodFormatterBuilder.java:1736)
	at org.joda.time.format.PeriodFormatter.parseMutablePeriod(PeriodFormatter.java:318)
	at org.joda.time.format.PeriodFormatter.parsePeriod(PeriodFormatter.java:304)
	at org.joda.time.Minutes.parseMinutes(Minutes.java:185)
	at org.joda.time.TestMinutes.__CLR4_4_1obpn46ico(TestMinutes.java:98)
	at org.joda.time.TestMinutes.testFactory_parseMinutes_String385(TestMinutes.java:95)
</error>
  </testcase>
  <testcase name="testToStandardWeeks228" classname="org.joda.time.TestSeconds" time="0.002">
    <failure message="expected:&lt;P2W&gt; but was:&lt;P0W&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<P2W> but was:<P0W>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestSeconds.__CLR4_4_1ki8laujne(TestSeconds.java:81)
	at org.joda.time.TestSeconds.testToStandardWeeks228(TestSeconds.java:78)
]]></failure>
  </testcase>
  <testcase name="testMinus_Seconds230" classname="org.joda.time.TestSeconds" time="0"/>
  <testcase name="testSerialization226" classname="org.joda.time.TestSeconds" time="0.001"/>
  <testcase name="testIsLessThan231" classname="org.joda.time.TestSeconds" time="0.001"/>
  <testcase name="testMinus_int229" classname="org.joda.time.TestSeconds" time="0"/>
  <testcase name="testFactory_secondsBetween_RInstant227" classname="org.joda.time.TestSeconds" time="0.001"/>
  <testcase name="testToDateTimeTodayDefaultZone478" classname="org.joda.time.TestTimeOfDay_Basics" time="0.001"/>
  <testcase name="testWithField3477" classname="org.joda.time.TestTimeOfDay_Basics" time="0.001"/>
  <testcase name="testWithers479" classname="org.joda.time.TestTimeOfDay_Basics" time="0.001"/>
  <testcase name="testConstructor_ObjectString3476" classname="org.joda.time.TestTimeOfDay_Constructors" time="0.001">
    <failure message="expected:&lt;7&gt; but was:&lt;10&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<7> but was:<10>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestTimeOfDay_Constructors.__CLR4_4_1ynjoc2jso(TestTimeOfDay_Constructors.java:97)
	at org.joda.time.TestTimeOfDay_Constructors.testConstructor_ObjectString3476(TestTimeOfDay_Constructors.java:94)
]]></failure>
  </testcase>
  <testcase name="testPropertyGetMinute481" classname="org.joda.time.TestTimeOfDay_Properties" time="0.003"/>
  <testcase name="testPropertyAddWrapFieldHour482" classname="org.joda.time.TestTimeOfDay_Properties" time="0"/>
  <testcase name="testPropertyGetHourOfDay193" classname="org.joda.time.TestTimeOfDay_Properties" time="0.001"/>
  <testcase name="testPropertySetMinute475" classname="org.joda.time.TestTimeOfDay_Properties" time="0"/>
  <testcase name="testPropertySetMilli480" classname="org.joda.time.TestTimeOfDay_Properties" time="0.001">
    <failure message="expected:&lt;49&gt; but was:&lt;12&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<49> but was:<12>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestTimeOfDay_Properties.check(TestTimeOfDay_Properties.java:248)
	at org.joda.time.TestTimeOfDay_Properties.__CLR4_4_1q4vlq9juc(TestTimeOfDay_Properties.java:129)
	at org.joda.time.TestTimeOfDay_Properties.testPropertySetMilli480(TestTimeOfDay_Properties.java:125)
]]></failure>
  </testcase>
  <testcase name="testPropertyGetMaxMinValuesDay194" classname="org.joda.time.TestTimeOfDay_Properties" time="0.001"/>
  <testcase name="testToLocalDate24" classname="org.joda.time.TestYearMonthDay_Basics" time="0.001"/>
  <testcase name="testToDateTime_nullTime27" classname="org.joda.time.TestYearMonthDay_Basics" time="0"/>
  <testcase name="testToDateTime_DateTimeZone28" classname="org.joda.time.TestYearMonthDay_Basics" time="0"/>
  <testcase name="testToString_String_Locale471" classname="org.joda.time.TestYearMonthDay_Basics" time="0.002"/>
  <testcase name="testToString_String_Locale624" classname="org.joda.time.TestYearMonthDay_Basics" time="0.001">
    <failure message="expected:&lt;[]10:20:30.040&gt; but was:&lt;[T]10:20:30.040&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<[]10:20:30.040> but was:<[T]10:20:30.040>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestYearMonthDay_Basics.__CLR4_4_1jrhdjsk0h(TestYearMonthDay_Basics.java:161)
	at org.joda.time.TestYearMonthDay_Basics.testToString_String_Locale624(TestYearMonthDay_Basics.java:158)
]]></failure>
  </testcase>
  <testcase name="testMinus_RP20" classname="org.joda.time.TestYearMonthDay_Basics" time="0.001">
    <failure message="expected:&lt;2001-03-03&gt; but was:&lt;2001-04-02&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<2001-03-03> but was:<2001-04-02>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestYearMonthDay_Basics.__CLR4_4_1g6a01ojyt(TestYearMonthDay_Basics.java:93)
	at org.joda.time.TestYearMonthDay_Basics.testMinus_RP20(TestYearMonthDay_Basics.java:89)
]]></failure>
  </testcase>
  <testcase name="testToString31" classname="org.joda.time.TestYearMonthDay_Basics" time="0.001"/>
  <testcase name="testWithChronologyRetainFields_sameChrono19" classname="org.joda.time.TestYearMonthDay_Basics" time="0"/>
  <testcase name="testPlusYears_int21" classname="org.joda.time.TestYearMonthDay_Basics" time="0.001"/>
  <testcase name="testPlusMonths_int22" classname="org.joda.time.TestYearMonthDay_Basics" time="0"/>
  <testcase name="testMinusDays_int23" classname="org.joda.time.TestYearMonthDay_Basics" time="0.001"/>
  <testcase name="testConstructor_ObjectString279" classname="org.joda.time.TestYearMonthDay_Constructors" time="0.001"/>
  <testcase name="testPropertyCompareToDay192" classname="org.joda.time.TestYearMonthDay_Properties" time="0"/>
  <testcase name="testPropertySetMonth13" classname="org.joda.time.TestYearMonthDay_Properties" time="0.001"/>
  <testcase name="testGetFieldType17" classname="org.joda.time.TestYearMonthDay_Properties" time="0.001"/>
  <testcase name="testPropertyGetMonth32" classname="org.joda.time.TestYearMonthDay_Properties" time="0"/>
  <testcase name="testPropertyWithMaximumValueDayOfMonth33" classname="org.joda.time.TestYearMonthDay_Properties" time="0.001"/>
  <testcase name="testProperty191" classname="org.joda.time.TestYearMonthDay_Properties" time="0.002"/>
  <testcase name="testMinusMonths_int163" classname="org.joda.time.TestYearMonth_Basics" time="0.001"/>
  <testcase name="testWithChronologyRetainFields_invalidInNewChrono162" classname="org.joda.time.TestYearMonth_Basics" time="0"/>
  <testcase name="testPlusYears_int166" classname="org.joda.time.TestYearMonth_Basics" time="0.001"/>
  <testcase name="testPlusMonths_int167" classname="org.joda.time.TestYearMonth_Basics" time="0"/>
  <testcase name="testToLocalDate169" classname="org.joda.time.TestYearMonth_Basics" time="0.001">
    <error message="Value 2009 for dayOfMonth must be in the range [1,30]" type="org.joda.time.IllegalFieldValueException"><![CDATA[org.joda.time.IllegalFieldValueException: Value 2009 for dayOfMonth must be in the range [1,30]
	at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:254)
	at org.joda.time.chrono.BasicChronology.getDateMidnightMillis(BasicChronology.java:613)
	at org.joda.time.chrono.BasicChronology.getDateTimeMillis(BasicChronology.java:159)
	at org.joda.time.chrono.CopticChronology.getDateTimeMillis(CopticChronology.java:51)
	at org.joda.time.chrono.LimitChronology.getDateTimeMillis(LimitChronology.java:177)
	at org.joda.time.chrono.BasicChronology.getDateTimeMillis(BasicChronology.java:154)
	at org.joda.time.chrono.CopticChronology.getDateTimeMillis(CopticChronology.java:51)
	at org.joda.time.LocalDate.<init>(LocalDate.java:457)
	at org.joda.time.YearMonth.toLocalDate(YearMonth.java:669)
	at org.joda.time.TestYearMonth_Basics.__CLR4_4_1o7znxrk5u(TestYearMonth_Basics.java:145)
	at org.joda.time.TestYearMonth_Basics.testToLocalDate169(TestYearMonth_Basics.java:143)
]]></error>
  </testcase>
  <testcase name="testGetFieldTypes161" classname="org.joda.time.TestYearMonth_Basics" time="0.001"/>
  <testcase name="testPlus_RP165" classname="org.joda.time.TestYearMonth_Basics" time="0"/>
  <testcase name="testMinus_RP164" classname="org.joda.time.TestYearMonth_Basics" time="0.001">
    <failure message="expected:&lt;2001-03&gt; but was:&lt;2001-04&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<2001-03> but was:<2001-04>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestYearMonth_Basics.__CLR4_4_1cgags7k52(TestYearMonth_Basics.java:115)
	at org.joda.time.TestYearMonth_Basics.testMinus_RP164(TestYearMonth_Basics.java:111)
]]></failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0.001">
    <failure message="No tests found in org.joda.time.TestYearMonth_Constructors" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestYearMonth_Constructors
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testPropertyGetMonth175" classname="org.joda.time.TestYearMonth_Properties" time="0.001"/>
  <testcase name="testPropertyEqualsHashCodeLenient174" classname="org.joda.time.TestYearMonth_Properties" time="0.001"/>
  <testcase name="testGet8" classname="org.joda.time.TestYearMonth_Properties" time="0.002">
    <failure message="expected:&lt;10&gt; but was:&lt;0&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<10> but was:<0>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestYearMonth_Properties.__CLR4_4_1b5fkytk76(TestYearMonth_Properties.java:85)
	at org.joda.time.TestYearMonth_Properties.testGet8(TestYearMonth_Properties.java:83)
]]></failure>
  </testcase>
  <testcase name="testMinusMonths_int528" classname="org.joda.time.TestMonthDay_Basics" time="0.002">
    <failure message="expected:&lt;--02-03&gt; but was:&lt;--01-03&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<--02-03> but was:<--01-03>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestMonthDay_Basics.__CLR4_4_15133q7ifq(TestMonthDay_Basics.java:137)
	at org.joda.time.TestMonthDay_Basics.testMinusMonths_int528(TestMonthDay_Basics.java:133)
]]></failure>
  </testcase>
  <testcase name="testMinusDays_int529" classname="org.joda.time.TestMonthDay_Basics" time="0.001">
    <failure message="expected:&lt;--05-11&gt; but was:&lt;--05-09&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<--05-11> but was:<--05-09>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestMonthDay_Basics.__CLR4_4_1qpcs4eifx(TestMonthDay_Basics.java:145)
	at org.joda.time.TestMonthDay_Basics.testMinusDays_int529(TestMonthDay_Basics.java:141)
]]></failure>
  </testcase>
  <testcase name="testMinusDays_int530" classname="org.joda.time.TestMonthDay_Basics" time="0.001">
    <failure message="expected:&lt;--05-10&gt; but was:&lt;--05-09&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<--05-10> but was:<--05-09>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestMonthDay_Basics.__CLR4_4_1r67zjoig4(TestMonthDay_Basics.java:153)
	at org.joda.time.TestMonthDay_Basics.testMinusDays_int530(TestMonthDay_Basics.java:149)
]]></failure>
  </testcase>
  <testcase name="testToString_String_Locale531" classname="org.joda.time.TestMonthDay_Basics" time="0.001">
    <failure message="expected:&lt;[--06-0]6&gt; but was:&lt;[� 6/]6&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<[--06-0]6> but was:<[� 6/]6>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestMonthDay_Basics.__CLR4_4_1t5wze5igb(TestMonthDay_Basics.java:159)
	at org.joda.time.TestMonthDay_Basics.testToString_String_Locale531(TestMonthDay_Basics.java:157)
]]></failure>
  </testcase>
  <testcase name="testToString_String_Locale532" classname="org.joda.time.TestMonthDay_Basics" time="0.004">
    <failure message="expected:&lt;[--06-06]&gt; but was:&lt;[06 ��]&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<[--06-06]> but was:<[06 ��]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestMonthDay_Basics.__CLR4_4_1pwx0loigh(TestMonthDay_Basics.java:166)
	at org.joda.time.TestMonthDay_Basics.testToString_String_Locale532(TestMonthDay_Basics.java:164)
]]></failure>
  </testcase>
  <testcase name="testEqualsHashCode521" classname="org.joda.time.TestMonthDay_Basics" time="0"/>
  <testcase name="testWithChronologyRetainFields_sameChrono524" classname="org.joda.time.TestMonthDay_Basics" time="0"/>
  <testcase name="testGetFieldTypes525" classname="org.joda.time.TestMonthDay_Basics" time="0.001">
    <error message="2" type="java.lang.ArrayIndexOutOfBoundsException">java.lang.ArrayIndexOutOfBoundsException: 2
	at org.joda.time.TestMonthDay_Basics.__CLR4_4_1r4i9jwif8(TestMonthDay_Basics.java:117)
	at org.joda.time.TestMonthDay_Basics.testGetFieldTypes525(TestMonthDay_Basics.java:112)
</error>
  </testcase>
  <testcase name="testGetFieldTypes526" classname="org.joda.time.TestMonthDay_Basics" time="0.001"/>
  <testcase name="testWithField_same527" classname="org.joda.time.TestMonthDay_Basics" time="0"/>
  <testcase name="testConstructor520" classname="org.joda.time.TestMonthDay_Constructors" time="0.001"/>
  <testcase name="testPropertyAddMonthOfYear533" classname="org.joda.time.TestMonthDay_Properties" time="0.001">
    <failure message="expected:&lt;2&gt; but was:&lt;12&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<2> but was:<12>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMonthDay_Properties.check(TestMonthDay_Properties.java:158)
	at org.joda.time.TestMonthDay_Properties.__CLR4_4_1e9gbj2ii9(TestMonthDay_Properties.java:98)
	at org.joda.time.TestMonthDay_Properties.testPropertyAddMonthOfYear533(TestMonthDay_Properties.java:92)
]]></failure>
  </testcase>
  <testcase name="testPropertySetTextDayOfMonth534" classname="org.joda.time.TestMonthDay_Properties" time="0.001">
    <failure message="expected:&lt;12&gt; but was:&lt;10&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<12> but was:<10>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMonthDay_Properties.check(TestMonthDay_Properties.java:158)
	at org.joda.time.TestMonthDay_Properties.__CLR4_4_15sfcm0iim(TestMonthDay_Properties.java:110)
	at org.joda.time.TestMonthDay_Properties.testPropertySetTextDayOfMonth534(TestMonthDay_Properties.java:106)
]]></failure>
  </testcase>
  <testcase name="testPropertySetTextDayOfMonth535" classname="org.joda.time.TestMonthDay_Properties" time="0.001">
    <failure message="expected:&lt;6&gt; but was:&lt;12&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<6> but was:<12>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMonthDay_Properties.check(TestMonthDay_Properties.java:159)
	at org.joda.time.TestMonthDay_Properties.__CLR4_4_12jfdtjiir(TestMonthDay_Properties.java:116)
	at org.joda.time.TestMonthDay_Properties.testPropertySetTextDayOfMonth535(TestMonthDay_Properties.java:112)
]]></failure>
  </testcase>
  <testcase name="testPropertyAddMonthOfYear198" classname="org.joda.time.TestMonthDay_Properties" time="0.002">
    <failure message="expected:&lt;3&gt; but was:&lt;12&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<3> but was:<12>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.TestMonthDay_Properties.check(TestMonthDay_Properties.java:158)
	at org.joda.time.TestMonthDay_Properties.__CLR4_4_1o98gsjihy(TestMonthDay_Properties.java:84)
	at org.joda.time.TestMonthDay_Properties.testPropertyAddMonthOfYear198(TestMonthDay_Properties.java:80)
]]></failure>
  </testcase>
  <testcase name="testToString5275" classname="org.joda.time.TestPartial_Basics" time="0.009"/>
  <testcase name="testToString2274" classname="org.joda.time.TestPartial_Basics" time="0"/>
  <testcase name="testToString_String_Locale467" classname="org.joda.time.TestPartial_Basics" time="0"/>
  <testcase name="testToString_String468" classname="org.joda.time.TestPartial_Basics" time="0"/>
  <testcase name="testGetFormatter1270" classname="org.joda.time.TestPartial_Constructors" time="0"/>
  <testcase name="testWith3f271" classname="org.joda.time.TestPartial_Constructors" time="0"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestPartial_Properties" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestPartial_Properties
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestPartial_Match" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestPartial_Match
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testGetField5" classname="org.joda.time.TestAbstractPartial" time="0">
    <failure message="expected same:&lt;DateTimeField[hourOfDay]&gt; was not:&lt;DateTimeField[year]&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected same:<DateTimeField[hourOfDay]> was not:<DateTimeField[year]>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotSame(Assert.java:276)
	at junit.framework.Assert.assertSame(Assert.java:239)
	at junit.framework.Assert.assertSame(Assert.java:246)
	at org.joda.time.TestAbstractPartial.__CLR4_4_1c70n6ugpg(TestAbstractPartial.java:106)
	at org.joda.time.TestAbstractPartial.testGetField5(TestAbstractPartial.java:104)
]]></failure>
  </testcase>
  <testcase name="testGetField4" classname="org.joda.time.TestAbstractPartial" time="0.006"/>
  <testcase name="testGetFieldTypes2" classname="org.joda.time.TestAbstractPartial" time="0">
    <error message="2" type="java.lang.ArrayIndexOutOfBoundsException">java.lang.ArrayIndexOutOfBoundsException: 2
	at org.joda.time.TestAbstractPartial.__CLR4_4_13u7okqgoz(TestAbstractPartial.java:86)
	at org.joda.time.TestAbstractPartial.testGetFieldTypes2(TestAbstractPartial.java:81)
</error>
  </testcase>
  <testcase name="testPlusDays_int1" classname="org.joda.time.TestAbstractPartial" time="0"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestBasePartial" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestBasePartial
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testStaticGetInstanceLower219" classname="org.joda.time.TestDateTimeComparator" time="0">
    <failure message="expected same:&lt;DateTimeComparator[]&gt; was not:&lt;DateTimeComparator[-hourOfDay]&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected same:<DateTimeComparator[]> was not:<DateTimeComparator[-hourOfDay]>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotSame(Assert.java:276)
	at junit.framework.Assert.assertSame(Assert.java:239)
	at junit.framework.Assert.assertSame(Assert.java:246)
	at org.joda.time.TestDateTimeComparator.__CLR4_4_1ew9d2jh09(TestDateTimeComparator.java:188)
	at org.joda.time.TestDateTimeComparator.testStaticGetInstanceLower219(TestDateTimeComparator.java:182)
]]></failure>
  </testcase>
  <testcase name="testStaticGetDateOnlyInstance220" classname="org.joda.time.TestDateTimeComparator" time="0"/>
  <testcase name="testPropertyRemainderHourOfDay125" classname="org.joda.time.TestDateTimeComparator" time="0.001"/>
  <testcase name="testStaticGetTimeOnlyInstance221" classname="org.joda.time.TestDateTimeComparator" time="0.002">
    <failure message="expected:&lt;dayOfYear&gt; but was:&lt;null&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<dayOfYear> but was:<null>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestDateTimeComparator.__CLR4_4_12xpmcsh0m(TestDateTimeComparator.java:199)
	at org.joda.time.TestDateTimeComparator.testStaticGetTimeOnlyInstance221(TestDateTimeComparator.java:197)
]]></failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestDateTimeConstants" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestDateTimeConstants
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestDateTimeUtils" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestDateTimeUtils
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testWithMinuteOfHourInDstChange_mockZone358" classname="org.joda.time.TestDateTimeZone" time="0.005"/>
  <testcase name="test_DateTimeZone359" classname="org.joda.time.TestDateTimeZone" time="0">
    <failure type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.fail(Assert.java:53)
	at org.joda.time.TestDateTimeZone.__CLR4_4_1ecto9ih5b(TestDateTimeZone.java:197)
	at org.joda.time.TestDateTimeZone.test_DateTimeZone359(TestDateTimeZone.java:194)
</failure>
  </testcase>
  <testcase name="testSetDayOfMonth_int_dstOverlapSummer_addZero266" classname="org.joda.time.TestDateTimeZone" time="0"/>
  <testcase name="testProvider_badClassName267" classname="org.joda.time.TestDateTimeZone" time="0.002"/>
  <testcase name="testSetMonthOfYear_int_dstOverlapSummer_addZero101" classname="org.joda.time.TestDateTimeZoneCutover" time="0.003"/>
  <testcase name="test_DateTime_plusHour_NewYork_Autumn259" classname="org.joda.time.TestDateTimeZoneCutover" time="0.002">
    <failure message="expected:&lt;2007-11-04T[02]:00:00.000-05:00&gt; but was:&lt;2007-11-04T[14]:00:00.000-05:00&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<2007-11-04T[02]:00:00.000-05:00> but was:<2007-11-04T[14]:00:00.000-05:00>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestDateTimeZoneCutover.__CLR4_4_1qlx7ylh7g(TestDateTimeZoneCutover.java:71)
	at org.joda.time.TestDateTimeZoneCutover.test_DateTime_plusHour_NewYork_Autumn259(TestDateTimeZoneCutover.java:67)
]]></failure>
  </testcase>
  <testcase name="testBug3192457_adjustOffset361" classname="org.joda.time.TestDateTimeZoneCutover" time="0.004"/>
  <testcase name="testMaskHours336" classname="org.joda.time.TestPeriodType" time="0.001">
    <failure message="expected:&lt;hours&gt; but was:&lt;minutes&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<hours> but was:<minutes>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestPeriodType.__CLR4_4_1x9wxccjd1(TestPeriodType.java:249)
	at org.joda.time.TestPeriodType.testMaskHours336(TestPeriodType.java:242)
]]></failure>
  </testcase>
  <testcase name="testForFields5325" classname="org.joda.time.TestPeriodType" time="0.001"/>
  <testcase name="testForFields6324" classname="org.joda.time.TestPeriodType" time="0"/>
  <testcase name="testToString331" classname="org.joda.time.TestPeriodType" time="0.001">
    <failure message="expected:&lt;PeriodType[[dayTime]]&gt; but was:&lt;PeriodType[[DayTimeNoMillis]]&gt;" type="junit.framework.ComparisonFailure">junit.framework.ComparisonFailure: expected:&lt;PeriodType[[dayTime]]&gt; but was:&lt;PeriodType[[DayTimeNoMillis]]&gt;	at junit.framework.Assert.assertEquals(Assert.java:81)	at junit.framework.Assert.assertEquals(Assert.java:87)	at org.joda.time.TestPeriodType.__CLR4_4_1ad91yejbd(TestPeriodType.java:180)	at org.joda.time.TestPeriodType.testToString331(TestPeriodType.java:178)</failure>
  </testcase>
  <testcase name="testName328" classname="org.joda.time.TestPeriodType" time="0.001">
    <failure message="expected:&lt;[dayTime]&gt; but was:&lt;[DayTimeNoMillis]&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<[dayTime]> but was:<[DayTimeNoMillis]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.TestPeriodType.__CLR4_4_19vuhwjjat(TestPeriodType.java:159)
	at org.joda.time.TestPeriodType.testName328(TestPeriodType.java:157)
]]></failure>
  </testcase>
  <testcase name="testMaskDays335" classname="org.joda.time.TestPeriodType" time="0.001">
    <failure message="expected:&lt;months&gt; but was:&lt;years&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<months> but was:<years>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestPeriodType.__CLR4_4_1nymjtzjci(TestPeriodType.java:225)
	at org.joda.time.TestPeriodType.testMaskDays335(TestPeriodType.java:222)
]]></failure>
  </testcase>
  <testcase name="testForFields6326" classname="org.joda.time.TestPeriodType" time="0.002">
    <error message="PeriodType does not support fields: [centuries]" type="java.lang.IllegalArgumentException">java.lang.IllegalArgumentException: PeriodType does not support fields: [centuries]
	at org.joda.time.PeriodType.forFields(PeriodType.java:536)
	at org.joda.time.TestPeriodType.__CLR4_4_18548k8jae(TestPeriodType.java:143)
	at org.joda.time.TestPeriodType.testForFields6326(TestPeriodType.java:141)
</error>
  </testcase>
  <testcase name="testMaskWeeks334" classname="org.joda.time.TestPeriodType" time="0.003">
    <failure message="expected:&lt;weeks&gt; but was:&lt;days&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<weeks> but was:<days>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestPeriodType.__CLR4_4_1i1hy56jbz(TestPeriodType.java:207)
	at org.joda.time.TestPeriodType.testMaskWeeks334(TestPeriodType.java:202)
]]></failure>
  </testcase>
  <testcase name="testMaskMonths333" classname="org.joda.time.TestPeriodType" time="0">
    <failure message="expected:&lt;months&gt; but was:&lt;years&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<months> but was:<years>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestPeriodType.__CLR4_4_1r1i9knjbg(TestPeriodType.java:185)
	at org.joda.time.TestPeriodType.testMaskMonths333(TestPeriodType.java:182)
]]></failure>
  </testcase>
  <testcase name="testMaskSeconds337" classname="org.joda.time.TestPeriodType" time="0.001">
    <failure message="expected:&lt;seconds&gt; but was:&lt;years&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<seconds> but was:<years>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestPeriodType.__CLR4_4_1ifsddpjdk(TestPeriodType.java:265)
	at org.joda.time.TestPeriodType.testMaskSeconds337(TestPeriodType.java:262)
]]></failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0.001">
    <failure message="No tests found in org.joda.time.TestDurationField" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestDurationField
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestStringConvert" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestStringConvert
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testSerializedMutableDateTimeProperty445" classname="org.joda.time.TestSerialization" time="0.016"/>
  <testcase name="testSerializedMutableDateTimeProperty446" classname="org.joda.time.TestSerialization" time="0.003">
    <failure message="expected:&lt;Property[monthOfYear]&gt; but was:&lt;Property[hourOfDay]&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<Property[monthOfYear]> but was:<Property[hourOfDay]>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.TestSerialization.loadAndCompare(TestSerialization.java:229)
	at org.joda.time.TestSerialization.__CLR4_4_1va1wqrjpq(TestSerialization.java:163)
	at org.joda.time.TestSerialization.testSerializedMutableDateTimeProperty446(TestSerialization.java:161)
]]></failure>
  </testcase>
  <testcase name="testPatchedNameKeysLondon126" classname="org.joda.time.TestSerialization" time="0.005"/>
  <testcase name="testFactory_Zone_int391" classname="org.joda.time.TestSerialization" time="0.001"/>
  <testcase name="testSerializedGJChronology68" classname="org.joda.time.TestSerialization" time="0.018"/>
  <testcase name="testFactory_millis_long116" classname="org.joda.time.TestSerialization" time="0.001"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.TestIllegalFieldValueException" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.TestIllegalFieldValueException
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.chrono.TestBuddhistChronology" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.chrono.TestBuddhistChronology
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testDurationFields142" classname="org.joda.time.chrono.TestCopticChronology" time="0"/>
  <testcase name="testWithZone140" classname="org.joda.time.chrono.TestCopticChronology" time="0.001"/>
  <testcase name="testWithUTC317" classname="org.joda.time.chrono.TestEthiopicChronology" time="0"/>
  <testcase name="testWithZone320" classname="org.joda.time.chrono.TestEthiopicChronology" time="0.001"/>
  <testcase name="testFactory_Zone_RI63" classname="org.joda.time.chrono.TestGJChronology" time="0.001"/>
  <testcase name="testLeapYearRulesConstruction71" classname="org.joda.time.chrono.TestGJChronology" time="0.001"/>
  <testcase name="testTimeOfDayAdd72" classname="org.joda.time.chrono.TestGJChronology" time="0.006"/>
  <testcase name="testCutoverAddYears61" classname="org.joda.time.chrono.TestGJChronology" time="0.012"/>
  <testcase name="testFactory_Zone62" classname="org.joda.time.chrono.TestGJChronology" time="0.001"/>
  <testcase name="testWithZone69" classname="org.joda.time.chrono.TestGJChronology" time="0"/>
  <testcase name="testFactory_Zone_RI65" classname="org.joda.time.chrono.TestGJChronology" time="0.001"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0.001">
    <failure message="No tests found in org.joda.time.chrono.TestGregorianChronology" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.chrono.TestGregorianChronology
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testEpoch58" classname="org.joda.time.chrono.TestIslamicChronology" time="0"/>
  <testcase name="testWithUTC54" classname="org.joda.time.chrono.TestIslamicChronology" time="0.001"/>
  <testcase name="testSampleDateWithZone56" classname="org.joda.time.chrono.TestIslamicChronology" time="0.001"/>
  <testcase name="testToString55" classname="org.joda.time.chrono.TestIslamicChronology" time="0"/>
  <testcase name="testFactoryUTC183" classname="org.joda.time.chrono.TestJulianChronology" time="0.001"/>
  <testcase name="testFactory_Zone_int186" classname="org.joda.time.chrono.TestJulianChronology" time="0.002"/>
  <testcase name="testFactory_Zone185" classname="org.joda.time.chrono.TestJulianChronology" time="0"/>
  <testcase name="testWithZone131" classname="org.joda.time.chrono.TestISOChronology" time="0.001"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.chrono.TestLenientChronology" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.chrono.TestLenientChronology
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.chrono.TestGJDate" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.chrono.TestGJDate
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testChronology" classname="org.joda.time.chrono.gj.MainTest" time="0.687"/>
  <testcase name="testChronology" classname="org.joda.time.chrono.gj.MainTest" time="0.472"/>
  <testcase name="testGetPeriodConverterRemovedNull212" classname="org.joda.time.convert.TestConverterManager" time="0.001">
    <failure type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.fail(Assert.java:53)
	at org.joda.time.convert.TestConverterManager.__CLR4_4_13juu7mlca(TestConverterManager.java:128)
	at org.joda.time.convert.TestConverterManager.testGetPeriodConverterRemovedNull212(TestConverterManager.java:123)
</failure>
  </testcase>
  <testcase name="testRemovePartialConverter2215" classname="org.joda.time.convert.TestConverterManager" time="0.001">
    <failure message="expected:&lt;Converter[java.lang.String]&gt; but was:&lt;null&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<Converter[java.lang.String]> but was:<null>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.convert.TestConverterManager.__CLR4_4_1f8ojk0ld9(TestConverterManager.java:207)
	at org.joda.time.convert.TestConverterManager.testRemovePartialConverter2215(TestConverterManager.java:182)
]]></failure>
  </testcase>
  <testcase name="testAddIntervalConverter1216" classname="org.joda.time.convert.TestConverterManager" time="0.001"/>
  <testcase name="testAddPartialConverter2214" classname="org.joda.time.convert.TestConverterManager" time="0"/>
  <testcase name="testGetPeriodConverterRemovedNull213" classname="org.joda.time.convert.TestConverterManager" time="0.001"/>
  <testcase name="testAddInstantConverter4210" classname="org.joda.time.convert.TestConverterManager" time="0"/>
  <testcase name="testBigHashtable459" classname="org.joda.time.convert.TestConverterSet" time="0.001"/>
  <testcase name="testRemoveNullRemoved3460" classname="org.joda.time.convert.TestConverterSet" time="0.001">
    <failure type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at org.joda.time.convert.TestConverterSet.__CLR4_4_1u7ujfflfa(TestConverterSet.java:100)
	at org.joda.time.convert.TestConverterSet.testRemoveNullRemoved3460(TestConverterSet.java:96)
</failure>
  </testcase>
  <testcase name="testGetInstantMillis_Object_Chronology565" classname="org.joda.time.convert.TestCalendarConverter" time="0.001">
    <failure message="expected:&lt;123&gt; but was:&lt;1676524832917&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<123> but was:<1676524832917>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:133)
	at junit.framework.Assert.assertEquals(Assert.java:139)
	at org.joda.time.convert.TestCalendarConverter.__CLR4_4_1o891ghlb5(TestCalendarConverter.java:81)
	at org.joda.time.convert.TestCalendarConverter.testGetInstantMillis_Object_Chronology565(TestCalendarConverter.java:79)
]]></failure>
  </testcase>
  <testcase name="testGetInstantMillis_Object_Chronology564" classname="org.joda.time.convert.TestCalendarConverter" time="0.001">
    <error message="java.util.Date cannot be cast to java.util.Calendar" type="java.lang.ClassCastException">java.lang.ClassCastException: java.util.Date cannot be cast to java.util.Calendar
	at org.joda.time.convert.CalendarConverter.getInstantMillis(CalendarConverter.java:121)
	at org.joda.time.convert.TestCalendarConverter.__CLR4_4_1rh908ylb0(TestCalendarConverter.java:75)
	at org.joda.time.convert.TestCalendarConverter.testGetInstantMillis_Object_Chronology564(TestCalendarConverter.java:73)
</error>
  </testcase>
  <testcase name="testGetChronology_Object_Chronology557" classname="org.joda.time.convert.TestCalendarConverter" time="0.001"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.convert.TestDateConverter" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.convert.TestDateConverter
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testGetDurationMillis_Object35" classname="org.joda.time.convert.TestLongConverter" time="0"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.convert.TestNullConverter" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.convert.TestNullConverter
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.convert.TestReadableDurationConverter" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.convert.TestReadableDurationConverter
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testGetDurationMillis_Object605" classname="org.joda.time.convert.TestReadableIntervalConverter" time="0.001">
    <failure message="expected:&lt;123&gt; but was:&lt;333&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<123> but was:<333>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:133)
	at junit.framework.Assert.assertEquals(Assert.java:139)
	at org.joda.time.convert.TestReadableIntervalConverter.__CLR4_4_1i30yg2lhp(TestReadableIntervalConverter.java:72)
	at org.joda.time.convert.TestReadableIntervalConverter.testGetDurationMillis_Object605(TestReadableIntervalConverter.java:71)
]]></failure>
  </testcase>
  <testcase name="testToString188" classname="org.joda.time.convert.TestReadableInstantConverter" time="0"/>
  <testcase name="testToString34" classname="org.joda.time.convert.TestReadablePartialConverter" time="0.004"/>
  <testcase name="testSetInto_Object82" classname="org.joda.time.convert.TestReadablePeriodConverter" time="0">
    <error message="Period does not support field &apos;weeks&apos;" type="java.lang.IllegalArgumentException">java.lang.IllegalArgumentException: Period does not support field 'weeks'
	at org.joda.time.base.BasePeriod.checkAndUpdate(BasePeriod.java:394)
	at org.joda.time.base.BasePeriod.setPeriodInternal(BasePeriod.java:424)
	at org.joda.time.base.BasePeriod.setPeriod(BasePeriod.java:412)
	at org.joda.time.MutablePeriod.setPeriod(MutablePeriod.java:468)
	at org.joda.time.convert.ReadablePeriodConverter.setInto(ReadablePeriodConverter.java:58)
	at org.joda.time.convert.TestReadablePeriodConverter.__CLR4_4_1vo7qghlip(TestReadablePeriodConverter.java:69)
	at org.joda.time.convert.TestReadablePeriodConverter.testSetInto_Object82(TestReadablePeriodConverter.java:67)
</error>
  </testcase>
  <testcase name="testSetIntoInterval_Object_Chronology580" classname="org.joda.time.convert.TestStringConverter" time="0.001"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0.001">
    <failure message="No tests found in org.joda.time.field.TestFieldUtils" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.field.TestFieldUtils
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="test_isSupported176" classname="org.joda.time.field.TestBaseDateTimeField" time="0"/>
  <testcase name="test_getAsText_RP_Locale177" classname="org.joda.time.field.TestBaseDateTimeField" time="0.001"/>
  <testcase name="test_roundHalfCeiling_long512" classname="org.joda.time.field.TestOffsetDateTimeField" time="0.001">
    <failure message="expected:&lt;0&gt; but was:&lt;-1000&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<0> but was:<-1000>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:133)
	at junit.framework.Assert.assertEquals(Assert.java:139)
	at org.joda.time.field.TestOffsetDateTimeField.__CLR4_4_1e5k8fplng(TestOffsetDateTimeField.java:60)
	at org.joda.time.field.TestOffsetDateTimeField.test_roundHalfCeiling_long512(TestOffsetDateTimeField.java:56)
]]></failure>
  </testcase>
  <testcase name="test_roundHalfEven_long513" classname="org.joda.time.field.TestOffsetDateTimeField" time="0.004"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.field.TestPreciseDurationDateTimeField" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.field.TestPreciseDurationDateTimeField
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="test_getRangeDurationField395" classname="org.joda.time.field.TestPreciseDateTimeField" time="0">
    <failure message="expected:&lt;null&gt; but was:&lt;DurationField[minutes]&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<null> but was:<DurationField[minutes]>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:71)
	at org.joda.time.field.TestPreciseDateTimeField.__CLR4_4_1wy2ickloi(TestPreciseDateTimeField.java:58)
	at org.joda.time.field.TestPreciseDateTimeField.test_getRangeDurationField395(TestPreciseDateTimeField.java:56)
]]></failure>
  </testcase>
  <testcase name="test_getDifference_long_long572" classname="org.joda.time.field.TestMillisDurationField" time="0"/>
  <testcase name="test_getValueAsLong_long571" classname="org.joda.time.field.TestMillisDurationField" time="0"/>
  <testcase name="test_Serialization574" classname="org.joda.time.field.TestMillisDurationField" time="0.004"/>
  <testcase name="test_add_long_int196" classname="org.joda.time.field.TestPreciseDurationField" time="0"/>
  <testcase name="testSerialization197" classname="org.joda.time.field.TestPreciseDurationField" time="0"/>
  <testcase name="test_getValue_long136" classname="org.joda.time.field.TestPreciseDurationField" time="0.001">
    <failure message="expected:&lt;12345&gt; but was:&lt;123&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<12345> but was:<123>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.field.TestPreciseDurationField.__CLR4_4_1w0uho8lt0(TestPreciseDurationField.java:66)
	at org.joda.time.field.TestPreciseDurationField.test_getValue_long136(TestPreciseDurationField.java:64)
]]></failure>
  </testcase>
  <testcase name="test_getValue_long137" classname="org.joda.time.field.TestPreciseDurationField" time="0.001">
    <failure message="expected:&lt;12345&gt; but was:&lt;123&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<12345> but was:<123>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:204)
	at org.joda.time.field.TestPreciseDurationField.__CLR4_4_1sruivrlt8(TestPreciseDurationField.java:77)
	at org.joda.time.field.TestPreciseDurationField.test_getValue_long137(TestPreciseDurationField.java:75)
]]></failure>
  </testcase>
  <testcase name="test_getMillis_int_long195" classname="org.joda.time.field.TestPreciseDurationField" time="0.001">
    <failure message="expected:&lt;1234&gt; but was:&lt;1234000&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<1234> but was:<1234000>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:133)
	at junit.framework.Assert.assertEquals(Assert.java:139)
	at org.joda.time.field.TestPreciseDurationField.__CLR4_4_1vivzi0ltg(TestPreciseDurationField.java:88)
	at org.joda.time.field.TestPreciseDurationField.test_getMillis_int_long195(TestPreciseDurationField.java:86)
]]></failure>
  </testcase>
  <testcase name="test_add_long_long129" classname="org.joda.time.field.TestScaledDurationField" time="0"/>
  <testcase name="test_getDifference_long_long130" classname="org.joda.time.field.TestScaledDurationField" time="0.002">
    <failure message="expected:&lt;1801&gt; but was:&lt;568&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<1801> but was:<568>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:133)
	at junit.framework.Assert.assertEquals(Assert.java:139)
	at org.joda.time.field.TestScaledDurationField.__CLR4_4_1jz6ittlus(TestScaledDurationField.java:84)
	at org.joda.time.field.TestScaledDurationField.test_getDifference_long_long130(TestScaledDurationField.java:80)
]]></failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.field.TestUnsupportedDateTimeField" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.field.TestUnsupportedDateTimeField
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testParseMutableDateTime_offsetParsed566" classname="org.joda.time.format.TestDateTimeFormatter" time="0.003"/>
  <testcase name="testParseLocalDate_weekyear_month_week_2011568" classname="org.joda.time.format.TestDateTimeFormatter" time="0.001"/>
  <testcase name="testParseInto_monthDay_feb29_tokyo_startOfYear567" classname="org.joda.time.format.TestDateTimeFormatter" time="0.001"/>
  <testcase name="testFormat_weekyear106" classname="org.joda.time.format.TestDateTimeFormat" time="0.001"/>
  <testcase name="testFormat_dayOfYear113" classname="org.joda.time.format.TestDateTimeFormat" time="0.004">
    <failure message="2004-06-09T10:20:30.040Z expected:&lt;[2004]&gt; but was:&lt;[Wed]&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: 2004-06-09T10:20:30.040Z expected:<[2004]> but was:<[Wed]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at org.joda.time.format.TestDateTimeFormat.__CLR4_4_1qg8pb4lwp(TestDateTimeFormat.java:105)
	at org.joda.time.format.TestDateTimeFormat.testFormat_dayOfYear113(TestDateTimeFormat.java:102)
]]></failure>
  </testcase>
  <testcase name="testForStyle_shortDate102" classname="org.joda.time.format.TestDateTimeFormatStyle" time="0.002">
    <failure message="expected same:&lt;org.joda.time.format.DateTimeFormatter@41d477ed&gt; was not:&lt;org.joda.time.format.DateTimeFormatter@3590fc5b&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected same:<org.joda.time.format.DateTimeFormatter@41d477ed> was not:<org.joda.time.format.DateTimeFormatter@3590fc5b>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotSame(Assert.java:276)
	at junit.framework.Assert.assertSame(Assert.java:239)
	at junit.framework.Assert.assertSame(Assert.java:246)
	at org.joda.time.format.TestDateTimeFormatStyle.__CLR4_4_164q423lxp(TestDateTimeFormatStyle.java:95)
	at org.joda.time.format.TestDateTimeFormatStyle.testForStyle_shortDate102(TestDateTimeFormatStyle.java:92)
]]></failure>
  </testcase>
  <testcase name="testForStyle_shortDateTime103" classname="org.joda.time.format.TestDateTimeFormatStyle" time="0.015"/>
  <testcase name="testFormat_dateHourMinuteSecondMillis379" classname="org.joda.time.format.TestISODateTimeFormat" time="0.002">
    <failure message="expected:&lt;2004-06-09T10:20:30[]&gt; but was:&lt;2004-06-09T10:20:30[.040]&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<2004-06-09T10:20:30[]> but was:<2004-06-09T10:20:30[.040]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.format.TestISODateTimeFormat.__CLR4_4_1ib5tqem2q(TestISODateTimeFormat.java:114)
	at org.joda.time.format.TestISODateTimeFormat.testFormat_dateHourMinuteSecondMillis379(TestISODateTimeFormat.java:112)
]]></failure>
  </testcase>
  <testcase name="testFormat_dateHourMinuteSecondFraction380" classname="org.joda.time.format.TestISODateTimeFormat" time="0.001">
    <failure message="expected:&lt;2004-06-09T10:20:30[]&gt; but was:&lt;2004-06-09T10:20:30[.040]&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<2004-06-09T10:20:30[]> but was:<2004-06-09T10:20:30[.040]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.format.TestISODateTimeFormat.__CLR4_4_1qus5nkm2x(TestISODateTimeFormat.java:122)
	at org.joda.time.format.TestISODateTimeFormat.testFormat_dateHourMinuteSecondFraction380(TestISODateTimeFormat.java:120)
]]></failure>
  </testcase>
  <testcase name="testFormat_yearMonthDay376" classname="org.joda.time.format.TestISODateTimeFormat" time="0.001"/>
  <testcase name="testFormat_weekyear377" classname="org.joda.time.format.TestISODateTimeFormat" time="0.001">
    <failure message="expected:&lt;2004[-W24]&gt; but was:&lt;2004[]&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<2004[-W24]> but was:<2004[]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.format.TestISODateTimeFormat.__CLR4_4_1v6jz8zm2c(TestISODateTimeFormat.java:98)
	at org.joda.time.format.TestISODateTimeFormat.testFormat_weekyear377(TestISODateTimeFormat.java:96)
]]></failure>
  </testcase>
  <testcase name="testFormat_weekyearWeekDay378" classname="org.joda.time.format.TestISODateTimeFormat" time="0.001"/>
  <testcase name="testForFields_calBased_YD367" classname="org.joda.time.format.TestISODateTimeFormat_Fields" time="0.004"/>
  <testcase name="testForFields_ordinalBased_D368" classname="org.joda.time.format.TestISODateTimeFormat_Fields" time="0"/>
  <testcase name="testForFields_weekBased_Y366" classname="org.joda.time.format.TestISODateTimeFormat_Fields" time="0.001"/>
  <testcase name="testForFields_weekBased_WD370" classname="org.joda.time.format.TestISODateTimeFormat_Fields" time="0.001"/>
  <testcase name="testForFields_weekBased_YD369" classname="org.joda.time.format.TestISODateTimeFormat_Fields" time="0"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.format.TestISODateTimeFormatParsing" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.format.TestISODateTimeFormatParsing
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="test_canBuildParser461" classname="org.joda.time.format.TestDateTimeFormatterBuilder" time="0"/>
  <testcase name="test_append_Printer463" classname="org.joda.time.format.TestDateTimeFormatterBuilder" time="0.001"/>
  <testcase name="test_append_Printer_nullParser462" classname="org.joda.time.format.TestDateTimeFormatterBuilder" time="0"/>
  <testcase name="test_append_Printer464" classname="org.joda.time.format.TestDateTimeFormatterBuilder" time="0.002">
    <failure message="expected:&lt;false&gt; but was:&lt;true&gt;" type="junit.framework.AssertionFailedError"><![CDATA[junit.framework.AssertionFailedError: expected:<false> but was:<true>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:280)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:146)
	at junit.framework.Assert.assertEquals(Assert.java:152)
	at org.joda.time.format.TestDateTimeFormatterBuilder.__CLR4_4_1mimzmfm0o(TestDateTimeFormatterBuilder.java:102)
	at org.joda.time.format.TestDateTimeFormatterBuilder.test_append_Printer464(TestDateTimeFormatterBuilder.java:93)
]]></failure>
  </testcase>
  <testcase name="test_printParseZoneParis509" classname="org.joda.time.format.TestDateTimeFormatterBuilder" time="0.008"/>
  <testcase name="test_append_Parser511" classname="org.joda.time.format.TestDateTimeFormatterBuilder" time="0.001"/>
  <testcase name="testPrint_writerMethods269" classname="org.joda.time.format.TestPeriodFormatter" time="0.001"/>
  <testcase name="test_wordBased_default315" classname="org.joda.time.format.TestPeriodFormat" time="0.005">
    <failure message="expected:&lt;1 [Tag, 5 Stunden, 6 Minuten, 7 Sekunden und 8 Millisekunden]&gt; but was:&lt;1 [day, 5 hours, 6 minutes, 7 seconds and 8 milliseconds]&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<1 [Tag, 5 Stunden, 6 Minuten, 7 Sekunden und 8 Millisekunden]> but was:<1 [day, 5 hours, 6 minutes, 7 seconds and 8 milliseconds]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.format.TestPeriodFormat.__CLR4_4_1m2d7j4m8r(TestPeriodFormat.java:68)
	at org.joda.time.format.TestPeriodFormat.test_wordBased_default315(TestPeriodFormat.java:66)
]]></failure>
  </testcase>
  <testcase name="test_wordBased_default316" classname="org.joda.time.format.TestPeriodFormat" time="0.003"/>
  <testcase name="testFormatAlternateExtended121" classname="org.joda.time.format.TestISOPeriodFormat" time="0.001">
    <failure message="expected:&lt;P0001-0[6-09]T05:06:07.008&gt; but was:&lt;P0001-0[2-04]T05:06:07.008&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<P0001-0[6-09]T05:06:07.008> but was:<P0001-0[2-04]T05:06:07.008>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.format.TestISOPeriodFormat.__CLR4_4_1ktux9m7g(TestISOPeriodFormat.java:95)
	at org.joda.time.format.TestISOPeriodFormat.testFormatAlternateExtended121(TestISOPeriodFormat.java:93)
]]></failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.format.TestISOPeriodFormatParsing" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.format.TestISOPeriodFormatParsing
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.format.TestPeriodFormatParsing" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.format.TestPeriodFormatParsing
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="testAppend_PrinterParser_Printer_null_null_Parser86" classname="org.joda.time.format.TestPeriodFormatterBuilder" time="0.001"/>
  <testcase name="testFormatPrefixSimple293" classname="org.joda.time.format.TestPeriodFormatterBuilder" time="0.001"/>
  <testcase name="testFormatPrintZeroRarelyLast87" classname="org.joda.time.format.TestPeriodFormatterBuilder" time="0.001">
    <failure message="expected:&lt;[0---]&gt; but was:&lt;[---0]&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<[0---]> but was:<[---0]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.format.TestPeriodFormatterBuilder.__CLR4_4_17x8g89mbc(TestPeriodFormatterBuilder.java:114)
	at org.joda.time.format.TestPeriodFormatterBuilder.testFormatPrintZeroRarelyLast87(TestPeriodFormatterBuilder.java:109)
]]></failure>
  </testcase>
  <testcase name="testFormatSeparatorIfFieldsAfter90" classname="org.joda.time.format.TestPeriodFormatterBuilder" time="0.002">
    <failure message="expected:&lt;[]5&gt; but was:&lt;[T]5&gt;" type="junit.framework.ComparisonFailure"><![CDATA[junit.framework.ComparisonFailure: expected:<[]5> but was:<[T]5>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at org.joda.time.format.TestPeriodFormatterBuilder.__CLR4_4_16qz6wmbz(TestPeriodFormatterBuilder.java:139)
	at org.joda.time.format.TestPeriodFormatterBuilder.testFormatSeparatorIfFieldsAfter90(TestPeriodFormatterBuilder.java:134)
]]></failure>
  </testcase>
  <testcase name="testFormatSeparatorSimple91" classname="org.joda.time.format.TestPeriodFormatterBuilder" time="0.001"/>
  <testcase name="testFormatAppend_PrinterParser_Printer_null_null_Parser99" classname="org.joda.time.format.TestPeriodFormatterBuilder" time="0.001"/>
  <testcase name="testBug249545595" classname="org.joda.time.format.TestPeriodFormatterBuilder" time="0.001"/>
  <testcase name="testFormatSuffixSimple289" classname="org.joda.time.format.TestPeriodFormatterBuilder" time="0"/>
  <testcase name="testFormatSeparatorIfFieldsBefore98" classname="org.joda.time.format.TestPeriodFormatterBuilder" time="0.001"/>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.format.TestTextFields" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.format.TestTextFields
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.tz.TestUTCProvider" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.tz.TestUTCProvider
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0.001">
    <failure message="No tests found in org.joda.time.tz.TestBuilder" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.tz.TestBuilder
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.tz.TestCompiler" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.tz.TestCompiler
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0.001">
    <failure message="No tests found in org.joda.time.tz.TestCachedDateTimeZone" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.tz.TestCachedDateTimeZone
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
  <testcase name="warning" classname="junit.framework.TestSuite$1" time="0">
    <failure message="No tests found in org.joda.time.tz.TestFixedDateTimeZone" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: No tests found in org.joda.time.tz.TestFixedDateTimeZone
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:90)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:120)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at junit.framework.TestSuite.runTest(TestSuite.java:230)
	at junit.framework.TestSuite.run(TestSuite.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:95)
	at org.apache.maven.surefire.junit.JUnit3Provider.executeTestSet(JUnit3Provider.java:131)
	at org.apache.maven.surefire.junit.JUnit3Provider.invoke(JUnit3Provider.java:108)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</failure>
  </testcase>
</testsuite>